// generated by gong
import { Component, OnInit, AfterViewInit, ViewChild, Inject, Optional } from '@angular/core';
import { BehaviorSubject } from 'rxjs'
import { MatSort } from '@angular/material/sort';
import { MatPaginator } from '@angular/material/paginator';
import { MatTableDataSource } from '@angular/material/table';
import { MatButton } from '@angular/material/button'

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData, FrontRepoService, FrontRepo, SelectionMode } from '../front-repo.service'
import { NullInt64 } from '../null-int64'
import { SelectionModel } from '@angular/cdk/collections';

const allowMultiSelect = true;

import { Router, RouterState } from '@angular/router';
import { ElementDB } from '../element-db'
import { ElementService } from '../element.service'

// insertion point for additional imports

// TableComponent is initilizaed from different routes
// TableComponentMode detail different cases 
enum TableComponentMode {
  DISPLAY_MODE,
  ONE_MANY_ASSOCIATION_MODE,
  MANY_MANY_ASSOCIATION_MODE,
}

// generated table component
@Component({
  selector: 'app-elementstable',
  templateUrl: './elements-table.component.html',
  styleUrls: ['./elements-table.component.css'],
})
export class ElementsTableComponent implements OnInit {

  // mode at invocation
  mode: TableComponentMode = TableComponentMode.DISPLAY_MODE

  // used if the component is called as a selection component of Element instances
  selection: SelectionModel<ElementDB> = new (SelectionModel)
  initialSelection = new Array<ElementDB>()

  // the data source for the table
  elements: ElementDB[] = []
  matTableDataSource: MatTableDataSource<ElementDB> = new (MatTableDataSource)

  // front repo, that will be referenced by this.elements
  frontRepo: FrontRepo = new (FrontRepo)

  // displayedColumns is referenced by the MatTable component for specify what columns
  // have to be displayed and in what order
  displayedColumns: string[];

  // for sorting & pagination
  @ViewChild(MatSort)
  sort: MatSort | undefined
  @ViewChild(MatPaginator)
  paginator: MatPaginator | undefined;

  ngAfterViewInit() {

    // enable sorting on all fields (including pointers and reverse pointer)
    this.matTableDataSource.sortingDataAccessor = (elementDB: ElementDB, property: string) => {
      switch (property) {
        case 'ID':
          return elementDB.ID

        // insertion point for specific sorting accessor
        case 'Name':
          return elementDB.Name;

        case 'Content':
          return elementDB.Content;

        case 'Type':
          return elementDB.Type;

        case 'Element_SubElements':
          if (this.frontRepo.Elements.get(elementDB.Element_SubElementsDBID.Int64) != undefined) {
            return this.frontRepo.Elements.get(elementDB.Element_SubElementsDBID.Int64)!.Name
          } else {
            return ""
          }

        default:
          console.assert(false, "Unknown field")
          return "";
      }
    };

    // enable filtering on all fields (including pointers and reverse pointer, which is not done by default)
    this.matTableDataSource.filterPredicate = (elementDB: ElementDB, filter: string) => {

      // filtering is based on finding a lower case filter into a concatenated string
      // the elementDB properties
      let mergedContent = ""

      // insertion point for merging of fields
      mergedContent += elementDB.Name.toLowerCase()
      mergedContent += elementDB.Content.toLowerCase()
      mergedContent += elementDB.Type.toLowerCase()
      if (elementDB.Element_SubElementsDBID.Int64 != 0) {
        mergedContent += this.frontRepo.Elements.get(elementDB.Element_SubElementsDBID.Int64)!.Name.toLowerCase()
      }


      let isSelected = mergedContent.includes(filter.toLowerCase())
      return isSelected
    };

    this.matTableDataSource.sort = this.sort!
    this.matTableDataSource.paginator = this.paginator!
  }

  applyFilter(event: Event) {
    const filterValue = (event.target as HTMLInputElement).value;
    this.matTableDataSource.filter = filterValue.trim().toLowerCase();
  }

  constructor(
    private elementService: ElementService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of element instances
    public dialogRef: MatDialogRef<ElementsTableComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {

    // compute mode
    if (dialogData == undefined) {
      this.mode = TableComponentMode.DISPLAY_MODE
    } else {
      switch (dialogData.SelectionMode) {
        case SelectionMode.ONE_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.ONE_MANY_ASSOCIATION_MODE
          break
        case SelectionMode.MANY_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.MANY_MANY_ASSOCIATION_MODE
          break
        default:
      }
    }

    // observable for changes in structs
    this.elementService.ElementServiceChanged.subscribe(
      message => {
        if (message == "post" || message == "update" || message == "delete") {
          this.getElements()
        }
      }
    )
    if (this.mode == TableComponentMode.DISPLAY_MODE) {
      this.displayedColumns = ['ID', 'Edit', 'Delete', // insertion point for columns to display
        "Name",
        "Content",
        "Type",
        "Element_SubElements",
      ]
    } else {
      this.displayedColumns = ['select', 'ID', // insertion point for columns to display
        "Name",
        "Content",
        "Type",
        "Element_SubElements",
      ]
      this.selection = new SelectionModel<ElementDB>(allowMultiSelect, this.initialSelection);
    }

  }

  ngOnInit(): void {
    this.getElements()
    this.matTableDataSource = new MatTableDataSource(this.elements)
  }

  getElements(): void {
    this.frontRepoService.pull().subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        this.elements = this.frontRepo.Elements_array;

        // insertion point for time duration Recoveries
        // insertion point for enum int Recoveries
        
        // in case the component is called as a selection component
        if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {
          for (let element of this.elements) {
            let ID = this.dialogData.ID
            let revPointer = element[this.dialogData.ReversePointer as keyof ElementDB] as unknown as NullInt64
            if (revPointer.Int64 == ID) {
              this.initialSelection.push(element)
            }
            this.selection = new SelectionModel<ElementDB>(allowMultiSelect, this.initialSelection);
          }
        }

        if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

          let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s" as keyof FrontRepo] as Map<number, ElementDB>
          let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)!

          let sourceField = sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]! as unknown as ElementDB[]
          for (let associationInstance of sourceField) {
            let element = associationInstance[this.dialogData.IntermediateStructField as keyof typeof associationInstance] as unknown as ElementDB
            this.initialSelection.push(element)
          }

          this.selection = new SelectionModel<ElementDB>(allowMultiSelect, this.initialSelection);
        }

        // update the mat table data source
        this.matTableDataSource.data = this.elements
      }
    )
  }

  // newElement initiate a new element
  // create a new Element objet
  newElement() {
  }

  deleteElement(elementID: number, element: ElementDB) {
    // list of elements is truncated of element before the delete
    this.elements = this.elements.filter(h => h !== element);

    this.elementService.deleteElement(elementID).subscribe(
      element => {
        this.elementService.ElementServiceChanged.next("delete")
      }
    );
  }

  editElement(elementID: number, element: ElementDB) {

  }

  // display element in router
  displayElementInRouter(elementID: number) {
    this.router.navigate(["github_com_fullstack_lang_gongmarkdown_go-" + "element-display", elementID])
  }

  // set editor outlet
  setEditorRouterOutlet(elementID: number) {
    this.router.navigate([{
      outlets: {
        github_com_fullstack_lang_gongmarkdown_go_editor: ["github_com_fullstack_lang_gongmarkdown_go-" + "element-detail", elementID]
      }
    }]);
  }

  // set presentation outlet
  setPresentationRouterOutlet(elementID: number) {
    this.router.navigate([{
      outlets: {
        github_com_fullstack_lang_gongmarkdown_go_presentation: ["github_com_fullstack_lang_gongmarkdown_go-" + "element-presentation", elementID]
      }
    }]);
  }

  /** Whether the number of selected elements matches the total number of rows. */
  isAllSelected() {
    const numSelected = this.selection.selected.length;
    const numRows = this.elements.length;
    return numSelected === numRows;
  }

  /** Selects all rows if they are not all selected; otherwise clear selection. */
  masterToggle() {
    this.isAllSelected() ?
      this.selection.clear() :
      this.elements.forEach(row => this.selection.select(row));
  }

  save() {

    if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {

      let toUpdate = new Set<ElementDB>()

      // reset all initial selection of element that belong to element
      for (let element of this.initialSelection) {
        let index = element[this.dialogData.ReversePointer as keyof ElementDB] as unknown as NullInt64
        index.Int64 = 0
        index.Valid = true
        toUpdate.add(element)

      }

      // from selection, set element that belong to element
      for (let element of this.selection.selected) {
        let ID = this.dialogData.ID as number
        let reversePointer = element[this.dialogData.ReversePointer as keyof ElementDB] as unknown as NullInt64
        reversePointer.Int64 = ID
        reversePointer.Valid = true
        toUpdate.add(element)
      }


      // update all element (only update selection & initial selection)
      for (let element of toUpdate) {
        this.elementService.updateElement(element)
          .subscribe(element => {
            this.elementService.ElementServiceChanged.next("update")
          });
      }
    }

    if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

      // get the source instance via the map of instances in the front repo
      let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s" as keyof FrontRepo] as Map<number, ElementDB>
      let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)!

      // First, parse all instance of the association struct and remove the instance
      // that have unselect
      let unselectedElement = new Set<number>()
      for (let element of this.initialSelection) {
        if (this.selection.selected.includes(element)) {
          // console.log("element " + element.Name + " is still selected")
        } else {
          console.log("element " + element.Name + " has been unselected")
          unselectedElement.add(element.ID)
          console.log("is unselected " + unselectedElement.has(element.ID))
        }
      }

      // delete the association instance
      let associationInstance = sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]
      let element = associationInstance![this.dialogData.IntermediateStructField as keyof typeof associationInstance] as unknown as ElementDB
      if (unselectedElement.has(element.ID)) {
        this.frontRepoService.deleteService(this.dialogData.IntermediateStruct, associationInstance)


      }

      // is the source array is empty create it
      if (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance] == undefined) {
        (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance] as unknown as Array<ElementDB>) = new Array<ElementDB>()
      }

      // second, parse all instance of the selected
      if (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]) {
        this.selection.selected.forEach(
          element => {
            if (!this.initialSelection.includes(element)) {
              // console.log("element " + element.Name + " has been added to the selection")

              let associationInstance = {
                Name: sourceInstance["Name"] + "-" + element.Name,
              }

              let index = associationInstance[this.dialogData.IntermediateStructField + "ID" as keyof typeof associationInstance] as unknown as NullInt64
              index.Int64 = element.ID
              index.Valid = true

              let indexDB = associationInstance[this.dialogData.IntermediateStructField + "DBID" as keyof typeof associationInstance] as unknown as NullInt64
              indexDB.Int64 = element.ID
              index.Valid = true

              this.frontRepoService.postService(this.dialogData.IntermediateStruct, associationInstance)

            } else {
              // console.log("element " + element.Name + " is still selected")
            }
          }
        )
      }

      // this.selection = new SelectionModel<ElementDB>(allowMultiSelect, this.initialSelection);
    }

    // why pizza ?
    this.dialogRef.close('Pizza!');
  }
}
