// generated by ng_file_service_ts
import { Injectable, Component, Inject } from '@angular/core';
import { HttpClientModule, HttpParams } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { DOCUMENT, Location } from '@angular/common'

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs'
import { Observable, of } from 'rxjs'
import { catchError, map, tap } from 'rxjs/operators'

import { AnotherDummyDataAPI } from './anotherdummydata-api'
import { AnotherDummyData, CopyAnotherDummyDataToAnotherDummyDataAPI } from './anotherdummydata'

import { FrontRepo, FrontRepoService } from './front-repo.service';

// insertion point for imports

@Injectable({
  providedIn: 'root'
})
export class AnotherDummyDataService {

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  AnotherDummyDataServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private anotherdummydatasUrl: string

  constructor(
    private http: HttpClient,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
    let origin = this.document.location.origin

    // if debugging with ng, replace 4200 with 8080
    origin = origin.replace("4200", "8080")

    // compute path to the service
    this.anotherdummydatasUrl = origin + '/api/github.com/fullstack-lang/gongmarkdown/go/v1/anotherdummydatas';
  }

  /** GET anotherdummydatas from the server */
  // gets is more robust to refactoring
  gets(GONG__StackPath: string, frontRepo: FrontRepo): Observable<AnotherDummyDataAPI[]> {
    return this.getAnotherDummyDatas(GONG__StackPath, frontRepo)
  }
  getAnotherDummyDatas(GONG__StackPath: string, frontRepo: FrontRepo): Observable<AnotherDummyDataAPI[]> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    return this.http.get<AnotherDummyDataAPI[]>(this.anotherdummydatasUrl, { params: params })
      .pipe(
        tap(),
        catchError(this.handleError<AnotherDummyDataAPI[]>('getAnotherDummyDatas', []))
      );
  }

  /** GET anotherdummydata by id. Will 404 if id not found */
  // more robust API to refactoring
  get(id: number, GONG__StackPath: string, frontRepo: FrontRepo): Observable<AnotherDummyDataAPI> {
    return this.getAnotherDummyData(id, GONG__StackPath, frontRepo)
  }
  getAnotherDummyData(id: number, GONG__StackPath: string, frontRepo: FrontRepo): Observable<AnotherDummyDataAPI> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    const url = `${this.anotherdummydatasUrl}/${id}`;
    return this.http.get<AnotherDummyDataAPI>(url, { params: params }).pipe(
      // tap(_ => this.log(`fetched anotherdummydata id=${id}`)),
      catchError(this.handleError<AnotherDummyDataAPI>(`getAnotherDummyData id=${id}`))
    );
  }

  // postFront copy anotherdummydata to a version with encoded pointers and post to the back
  postFront(anotherdummydata: AnotherDummyData, GONG__StackPath: string): Observable<AnotherDummyDataAPI> {
    let anotherdummydataAPI = new AnotherDummyDataAPI
    CopyAnotherDummyDataToAnotherDummyDataAPI(anotherdummydata, anotherdummydataAPI)
    const id = typeof anotherdummydataAPI === 'number' ? anotherdummydataAPI : anotherdummydataAPI.ID
    const url = `${this.anotherdummydatasUrl}/${id}`;
    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<AnotherDummyDataAPI>(url, anotherdummydataAPI, httpOptions).pipe(
      tap(_ => {
      }),
      catchError(this.handleError<AnotherDummyDataAPI>('postAnotherDummyData'))
    );
  }
  
  /** POST: add a new anotherdummydata to the server */
  post(anotherdummydatadb: AnotherDummyDataAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<AnotherDummyDataAPI> {
    return this.postAnotherDummyData(anotherdummydatadb, GONG__StackPath, frontRepo)
  }
  postAnotherDummyData(anotherdummydatadb: AnotherDummyDataAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<AnotherDummyDataAPI> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<AnotherDummyDataAPI>(this.anotherdummydatasUrl, anotherdummydatadb, httpOptions).pipe(
      tap(_ => {
        // this.log(`posted anotherdummydatadb id=${anotherdummydatadb.ID}`)
      }),
      catchError(this.handleError<AnotherDummyDataAPI>('postAnotherDummyData'))
    );
  }

  /** DELETE: delete the anotherdummydatadb from the server */
  delete(anotherdummydatadb: AnotherDummyDataAPI | number, GONG__StackPath: string): Observable<AnotherDummyDataAPI> {
    return this.deleteAnotherDummyData(anotherdummydatadb, GONG__StackPath)
  }
  deleteAnotherDummyData(anotherdummydatadb: AnotherDummyDataAPI | number, GONG__StackPath: string): Observable<AnotherDummyDataAPI> {
    const id = typeof anotherdummydatadb === 'number' ? anotherdummydatadb : anotherdummydatadb.ID;
    const url = `${this.anotherdummydatasUrl}/${id}`;

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.delete<AnotherDummyDataAPI>(url, httpOptions).pipe(
      tap(_ => this.log(`deleted anotherdummydatadb id=${id}`)),
      catchError(this.handleError<AnotherDummyDataAPI>('deleteAnotherDummyData'))
    );
  }

  // updateFront copy anotherdummydata to a version with encoded pointers and update to the back
  updateFront(anotherdummydata: AnotherDummyData, GONG__StackPath: string): Observable<AnotherDummyDataAPI> {
    let anotherdummydataAPI = new AnotherDummyDataAPI
    CopyAnotherDummyDataToAnotherDummyDataAPI(anotherdummydata, anotherdummydataAPI)
    const id = typeof anotherdummydataAPI === 'number' ? anotherdummydataAPI : anotherdummydataAPI.ID
    const url = `${this.anotherdummydatasUrl}/${id}`;
    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.put<AnotherDummyDataAPI>(url, anotherdummydataAPI, httpOptions).pipe(
      tap(_ => {
      }),
      catchError(this.handleError<AnotherDummyDataAPI>('updateAnotherDummyData'))
    );
  }

  /** PUT: update the anotherdummydatadb on the server */
  update(anotherdummydatadb: AnotherDummyDataAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<AnotherDummyDataAPI> {
    return this.updateAnotherDummyData(anotherdummydatadb, GONG__StackPath, frontRepo)
  }
  updateAnotherDummyData(anotherdummydatadb: AnotherDummyDataAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<AnotherDummyDataAPI> {
    const id = typeof anotherdummydatadb === 'number' ? anotherdummydatadb : anotherdummydatadb.ID;
    const url = `${this.anotherdummydatasUrl}/${id}`;


    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.put<AnotherDummyDataAPI>(url, anotherdummydatadb, httpOptions).pipe(
      tap(_ => {
        // this.log(`updated anotherdummydatadb id=${anotherdummydatadb.ID}`)
      }),
      catchError(this.handleError<AnotherDummyDataAPI>('updateAnotherDummyData'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation in AnotherDummyDataService', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error("AnotherDummyDataService" + error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {
    console.log(message)
  }
}
