// generated by ng_file_service_ts
import { Injectable, Component, Inject } from '@angular/core';
import { HttpClientModule, HttpParams } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { DOCUMENT, Location } from '@angular/common'

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs'
import { Observable, of } from 'rxjs'
import { catchError, map, tap } from 'rxjs/operators'

import { DummyDataAPI } from './dummydata-api'
import { DummyData, CopyDummyDataToDummyDataAPI } from './dummydata'

import { FrontRepo, FrontRepoService } from './front-repo.service';

// insertion point for imports
import { AnotherDummyDataAPI } from './anotherdummydata-api'

@Injectable({
  providedIn: 'root'
})
export class DummyDataService {

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  DummyDataServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private dummydatasUrl: string

  constructor(
    private http: HttpClient,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
    let origin = this.document.location.origin

    // if debugging with ng, replace 4200 with 8080
    origin = origin.replace("4200", "8080")

    // compute path to the service
    this.dummydatasUrl = origin + '/api/github.com/fullstack-lang/gongmarkdown/go/v1/dummydatas';
  }

  /** GET dummydatas from the server */
  // gets is more robust to refactoring
  gets(GONG__StackPath: string, frontRepo: FrontRepo): Observable<DummyDataAPI[]> {
    return this.getDummyDatas(GONG__StackPath, frontRepo)
  }
  getDummyDatas(GONG__StackPath: string, frontRepo: FrontRepo): Observable<DummyDataAPI[]> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    return this.http.get<DummyDataAPI[]>(this.dummydatasUrl, { params: params })
      .pipe(
        tap(),
        catchError(this.handleError<DummyDataAPI[]>('getDummyDatas', []))
      );
  }

  /** GET dummydata by id. Will 404 if id not found */
  // more robust API to refactoring
  get(id: number, GONG__StackPath: string, frontRepo: FrontRepo): Observable<DummyDataAPI> {
    return this.getDummyData(id, GONG__StackPath, frontRepo)
  }
  getDummyData(id: number, GONG__StackPath: string, frontRepo: FrontRepo): Observable<DummyDataAPI> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    const url = `${this.dummydatasUrl}/${id}`;
    return this.http.get<DummyDataAPI>(url, { params: params }).pipe(
      // tap(_ => this.log(`fetched dummydata id=${id}`)),
      catchError(this.handleError<DummyDataAPI>(`getDummyData id=${id}`))
    );
  }

  // postFront copy dummydata to a version with encoded pointers and post to the back
  postFront(dummydata: DummyData, GONG__StackPath: string): Observable<DummyDataAPI> {
    let dummydataAPI = new DummyDataAPI
    CopyDummyDataToDummyDataAPI(dummydata, dummydataAPI)
    const id = typeof dummydataAPI === 'number' ? dummydataAPI : dummydataAPI.ID
    const url = `${this.dummydatasUrl}/${id}`;
    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<DummyDataAPI>(url, dummydataAPI, httpOptions).pipe(
      tap(_ => {
      }),
      catchError(this.handleError<DummyDataAPI>('postDummyData'))
    );
  }
  
  /** POST: add a new dummydata to the server */
  post(dummydatadb: DummyDataAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<DummyDataAPI> {
    return this.postDummyData(dummydatadb, GONG__StackPath, frontRepo)
  }
  postDummyData(dummydatadb: DummyDataAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<DummyDataAPI> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<DummyDataAPI>(this.dummydatasUrl, dummydatadb, httpOptions).pipe(
      tap(_ => {
        // this.log(`posted dummydatadb id=${dummydatadb.ID}`)
      }),
      catchError(this.handleError<DummyDataAPI>('postDummyData'))
    );
  }

  /** DELETE: delete the dummydatadb from the server */
  delete(dummydatadb: DummyDataAPI | number, GONG__StackPath: string): Observable<DummyDataAPI> {
    return this.deleteDummyData(dummydatadb, GONG__StackPath)
  }
  deleteDummyData(dummydatadb: DummyDataAPI | number, GONG__StackPath: string): Observable<DummyDataAPI> {
    const id = typeof dummydatadb === 'number' ? dummydatadb : dummydatadb.ID;
    const url = `${this.dummydatasUrl}/${id}`;

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.delete<DummyDataAPI>(url, httpOptions).pipe(
      tap(_ => this.log(`deleted dummydatadb id=${id}`)),
      catchError(this.handleError<DummyDataAPI>('deleteDummyData'))
    );
  }

  // updateFront copy dummydata to a version with encoded pointers and update to the back
  updateFront(dummydata: DummyData, GONG__StackPath: string): Observable<DummyDataAPI> {
    let dummydataAPI = new DummyDataAPI
    CopyDummyDataToDummyDataAPI(dummydata, dummydataAPI)
    const id = typeof dummydataAPI === 'number' ? dummydataAPI : dummydataAPI.ID
    const url = `${this.dummydatasUrl}/${id}`;
    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.put<DummyDataAPI>(url, dummydataAPI, httpOptions).pipe(
      tap(_ => {
      }),
      catchError(this.handleError<DummyDataAPI>('updateDummyData'))
    );
  }

  /** PUT: update the dummydatadb on the server */
  update(dummydatadb: DummyDataAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<DummyDataAPI> {
    return this.updateDummyData(dummydatadb, GONG__StackPath, frontRepo)
  }
  updateDummyData(dummydatadb: DummyDataAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<DummyDataAPI> {
    const id = typeof dummydatadb === 'number' ? dummydatadb : dummydatadb.ID;
    const url = `${this.dummydatasUrl}/${id}`;


    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.put<DummyDataAPI>(url, dummydatadb, httpOptions).pipe(
      tap(_ => {
        // this.log(`updated dummydatadb id=${dummydatadb.ID}`)
      }),
      catchError(this.handleError<DummyDataAPI>('updateDummyData'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation in DummyDataService', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error("DummyDataService" + error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {
    console.log(message)
  }
}
