// generated by ng_file_service_ts
import { Injectable, Component, Inject } from '@angular/core';
import { HttpClientModule } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { DOCUMENT, Location } from '@angular/common'

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs';
import { Observable, of } from 'rxjs';
import { catchError, map, tap } from 'rxjs/operators';

import { DummyDataDB } from './dummydata-db';

// insertion point for imports
import { AnotherDummyDataDB } from './anotherdummydata-db'

@Injectable({
  providedIn: 'root'
})
export class DummyDataService {

  httpOptions = {
    headers: new HttpHeaders({ 'Content-Type': 'application/json' })
  };

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  DummyDataServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private dummydatasUrl: string

  constructor(
    private http: HttpClient,
    private location: Location,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
    let origin = this.document.location.origin

    // if debugging with ng, replace 4200 with 8080
    origin = origin.replace("4200", "8080")

    // compute path to the service
    this.dummydatasUrl = origin + '/api/github.com/fullstack-lang/gongmarkdown/go/v1/dummydatas';
  }

  /** GET dummydatas from the server */
  getDummyDatas(): Observable<DummyDataDB[]> {
    return this.http.get<DummyDataDB[]>(this.dummydatasUrl)
      .pipe(
        tap(_ => this.log('fetched dummydatas')),
        catchError(this.handleError<DummyDataDB[]>('getDummyDatas', []))
      );
  }

  /** GET dummydata by id. Will 404 if id not found */
  getDummyData(id: number): Observable<DummyDataDB> {
    const url = `${this.dummydatasUrl}/${id}`;
    return this.http.get<DummyDataDB>(url).pipe(
      tap(_ => this.log(`fetched dummydata id=${id}`)),
      catchError(this.handleError<DummyDataDB>(`getDummyData id=${id}`))
    );
  }

  //////// Save methods //////////

  /** POST: add a new dummydata to the server */
  postDummyData(dummydatadb: DummyDataDB): Observable<DummyDataDB> {

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)
    dummydatadb.DummyPointerToGongStruct = new AnotherDummyDataDB

    return this.http.post<DummyDataDB>(this.dummydatasUrl, dummydatadb, this.httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        this.log(`posted dummydatadb id=${dummydatadb.ID}`)
      }),
      catchError(this.handleError<DummyDataDB>('postDummyData'))
    );
  }

  /** DELETE: delete the dummydatadb from the server */
  deleteDummyData(dummydatadb: DummyDataDB | number): Observable<DummyDataDB> {
    const id = typeof dummydatadb === 'number' ? dummydatadb : dummydatadb.ID;
    const url = `${this.dummydatasUrl}/${id}`;

    return this.http.delete<DummyDataDB>(url, this.httpOptions).pipe(
      tap(_ => this.log(`deleted dummydatadb id=${id}`)),
      catchError(this.handleError<DummyDataDB>('deleteDummyData'))
    );
  }

  /** PUT: update the dummydatadb on the server */
  updateDummyData(dummydatadb: DummyDataDB): Observable<DummyDataDB> {
    const id = typeof dummydatadb === 'number' ? dummydatadb : dummydatadb.ID;
    const url = `${this.dummydatasUrl}/${id}`;

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)
    dummydatadb.DummyPointerToGongStruct = new AnotherDummyDataDB

    return this.http.put<DummyDataDB>(url, dummydatadb, this.httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        this.log(`updated dummydatadb id=${dummydatadb.ID}`)
      }),
      catchError(this.handleError<DummyDataDB>('updateDummyData'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error(error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {

  }
}
