// generated by ng_file_service_ts
import { Injectable, Component, Inject } from '@angular/core';
import { HttpClientModule, HttpParams } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { DOCUMENT, Location } from '@angular/common'

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs'
import { Observable, of } from 'rxjs'
import { catchError, map, tap } from 'rxjs/operators'

import { ElementAPI } from './element-api'
import { Element, CopyElementToElementAPI } from './element'

import { FrontRepo, FrontRepoService } from './front-repo.service';

// insertion point for imports
import { RowAPI } from './row-api'

@Injectable({
  providedIn: 'root'
})
export class ElementService {

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  ElementServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private elementsUrl: string

  constructor(
    private http: HttpClient,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
    let origin = this.document.location.origin

    // if debugging with ng, replace 4200 with 8080
    origin = origin.replace("4200", "8080")

    // compute path to the service
    this.elementsUrl = origin + '/api/github.com/fullstack-lang/gongmarkdown/go/v1/elements';
  }

  /** GET elements from the server */
  // gets is more robust to refactoring
  gets(GONG__StackPath: string, frontRepo: FrontRepo): Observable<ElementAPI[]> {
    return this.getElements(GONG__StackPath, frontRepo)
  }
  getElements(GONG__StackPath: string, frontRepo: FrontRepo): Observable<ElementAPI[]> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    return this.http.get<ElementAPI[]>(this.elementsUrl, { params: params })
      .pipe(
        tap(),
        catchError(this.handleError<ElementAPI[]>('getElements', []))
      );
  }

  /** GET element by id. Will 404 if id not found */
  // more robust API to refactoring
  get(id: number, GONG__StackPath: string, frontRepo: FrontRepo): Observable<ElementAPI> {
    return this.getElement(id, GONG__StackPath, frontRepo)
  }
  getElement(id: number, GONG__StackPath: string, frontRepo: FrontRepo): Observable<ElementAPI> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    const url = `${this.elementsUrl}/${id}`;
    return this.http.get<ElementAPI>(url, { params: params }).pipe(
      // tap(_ => this.log(`fetched element id=${id}`)),
      catchError(this.handleError<ElementAPI>(`getElement id=${id}`))
    );
  }

  // postFront copy element to a version with encoded pointers and post to the back
  postFront(element: Element, GONG__StackPath: string): Observable<ElementAPI> {
    let elementAPI = new ElementAPI
    CopyElementToElementAPI(element, elementAPI)
    const id = typeof elementAPI === 'number' ? elementAPI : elementAPI.ID
    const url = `${this.elementsUrl}/${id}`;
    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<ElementAPI>(url, elementAPI, httpOptions).pipe(
      tap(_ => {
      }),
      catchError(this.handleError<ElementAPI>('postElement'))
    );
  }
  
  /** POST: add a new element to the server */
  post(elementdb: ElementAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<ElementAPI> {
    return this.postElement(elementdb, GONG__StackPath, frontRepo)
  }
  postElement(elementdb: ElementAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<ElementAPI> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<ElementAPI>(this.elementsUrl, elementdb, httpOptions).pipe(
      tap(_ => {
        // this.log(`posted elementdb id=${elementdb.ID}`)
      }),
      catchError(this.handleError<ElementAPI>('postElement'))
    );
  }

  /** DELETE: delete the elementdb from the server */
  delete(elementdb: ElementAPI | number, GONG__StackPath: string): Observable<ElementAPI> {
    return this.deleteElement(elementdb, GONG__StackPath)
  }
  deleteElement(elementdb: ElementAPI | number, GONG__StackPath: string): Observable<ElementAPI> {
    const id = typeof elementdb === 'number' ? elementdb : elementdb.ID;
    const url = `${this.elementsUrl}/${id}`;

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.delete<ElementAPI>(url, httpOptions).pipe(
      tap(_ => this.log(`deleted elementdb id=${id}`)),
      catchError(this.handleError<ElementAPI>('deleteElement'))
    );
  }

  // updateFront copy element to a version with encoded pointers and update to the back
  updateFront(element: Element, GONG__StackPath: string): Observable<ElementAPI> {
    let elementAPI = new ElementAPI
    CopyElementToElementAPI(element, elementAPI)
    const id = typeof elementAPI === 'number' ? elementAPI : elementAPI.ID
    const url = `${this.elementsUrl}/${id}`;
    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.put<ElementAPI>(url, elementAPI, httpOptions).pipe(
      tap(_ => {
      }),
      catchError(this.handleError<ElementAPI>('updateElement'))
    );
  }

  /** PUT: update the elementdb on the server */
  update(elementdb: ElementAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<ElementAPI> {
    return this.updateElement(elementdb, GONG__StackPath, frontRepo)
  }
  updateElement(elementdb: ElementAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<ElementAPI> {
    const id = typeof elementdb === 'number' ? elementdb : elementdb.ID;
    const url = `${this.elementsUrl}/${id}`;


    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.put<ElementAPI>(url, elementdb, httpOptions).pipe(
      tap(_ => {
        // this.log(`updated elementdb id=${elementdb.ID}`)
      }),
      catchError(this.handleError<ElementAPI>('updateElement'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation in ElementService', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error("ElementService" + error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {
    console.log(message)
  }
}
