// generated by ng_file_service_ts
import { Injectable, Component, Inject } from '@angular/core';
import { HttpClientModule, HttpParams } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { DOCUMENT, Location } from '@angular/common'

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs'
import { Observable, of } from 'rxjs'
import { catchError, map, tap } from 'rxjs/operators'

import { MarkdownContentAPI } from './markdowncontent-api'
import { MarkdownContent, CopyMarkdownContentToMarkdownContentAPI } from './markdowncontent'

import { FrontRepo, FrontRepoService } from './front-repo.service';

// insertion point for imports
import { ElementAPI } from './element-api'

@Injectable({
  providedIn: 'root'
})
export class MarkdownContentService {

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  MarkdownContentServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private markdowncontentsUrl: string

  constructor(
    private http: HttpClient,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
    let origin = this.document.location.origin

    // if debugging with ng, replace 4200 with 8080
    origin = origin.replace("4200", "8080")

    // compute path to the service
    this.markdowncontentsUrl = origin + '/api/github.com/fullstack-lang/gongmarkdown/go/v1/markdowncontents';
  }

  /** GET markdowncontents from the server */
  // gets is more robust to refactoring
  gets(GONG__StackPath: string, frontRepo: FrontRepo): Observable<MarkdownContentAPI[]> {
    return this.getMarkdownContents(GONG__StackPath, frontRepo)
  }
  getMarkdownContents(GONG__StackPath: string, frontRepo: FrontRepo): Observable<MarkdownContentAPI[]> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    return this.http.get<MarkdownContentAPI[]>(this.markdowncontentsUrl, { params: params })
      .pipe(
        tap(),
        catchError(this.handleError<MarkdownContentAPI[]>('getMarkdownContents', []))
      );
  }

  /** GET markdowncontent by id. Will 404 if id not found */
  // more robust API to refactoring
  get(id: number, GONG__StackPath: string, frontRepo: FrontRepo): Observable<MarkdownContentAPI> {
    return this.getMarkdownContent(id, GONG__StackPath, frontRepo)
  }
  getMarkdownContent(id: number, GONG__StackPath: string, frontRepo: FrontRepo): Observable<MarkdownContentAPI> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    const url = `${this.markdowncontentsUrl}/${id}`;
    return this.http.get<MarkdownContentAPI>(url, { params: params }).pipe(
      // tap(_ => this.log(`fetched markdowncontent id=${id}`)),
      catchError(this.handleError<MarkdownContentAPI>(`getMarkdownContent id=${id}`))
    );
  }

  // postFront copy markdowncontent to a version with encoded pointers and post to the back
  postFront(markdowncontent: MarkdownContent, GONG__StackPath: string): Observable<MarkdownContentAPI> {
    let markdowncontentAPI = new MarkdownContentAPI
    CopyMarkdownContentToMarkdownContentAPI(markdowncontent, markdowncontentAPI)
    const id = typeof markdowncontentAPI === 'number' ? markdowncontentAPI : markdowncontentAPI.ID
    const url = `${this.markdowncontentsUrl}/${id}`;
    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<MarkdownContentAPI>(url, markdowncontentAPI, httpOptions).pipe(
      tap(_ => {
      }),
      catchError(this.handleError<MarkdownContentAPI>('postMarkdownContent'))
    );
  }
  
  /** POST: add a new markdowncontent to the server */
  post(markdowncontentdb: MarkdownContentAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<MarkdownContentAPI> {
    return this.postMarkdownContent(markdowncontentdb, GONG__StackPath, frontRepo)
  }
  postMarkdownContent(markdowncontentdb: MarkdownContentAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<MarkdownContentAPI> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<MarkdownContentAPI>(this.markdowncontentsUrl, markdowncontentdb, httpOptions).pipe(
      tap(_ => {
        // this.log(`posted markdowncontentdb id=${markdowncontentdb.ID}`)
      }),
      catchError(this.handleError<MarkdownContentAPI>('postMarkdownContent'))
    );
  }

  /** DELETE: delete the markdowncontentdb from the server */
  delete(markdowncontentdb: MarkdownContentAPI | number, GONG__StackPath: string): Observable<MarkdownContentAPI> {
    return this.deleteMarkdownContent(markdowncontentdb, GONG__StackPath)
  }
  deleteMarkdownContent(markdowncontentdb: MarkdownContentAPI | number, GONG__StackPath: string): Observable<MarkdownContentAPI> {
    const id = typeof markdowncontentdb === 'number' ? markdowncontentdb : markdowncontentdb.ID;
    const url = `${this.markdowncontentsUrl}/${id}`;

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.delete<MarkdownContentAPI>(url, httpOptions).pipe(
      tap(_ => this.log(`deleted markdowncontentdb id=${id}`)),
      catchError(this.handleError<MarkdownContentAPI>('deleteMarkdownContent'))
    );
  }

  // updateFront copy markdowncontent to a version with encoded pointers and update to the back
  updateFront(markdowncontent: MarkdownContent, GONG__StackPath: string): Observable<MarkdownContentAPI> {
    let markdowncontentAPI = new MarkdownContentAPI
    CopyMarkdownContentToMarkdownContentAPI(markdowncontent, markdowncontentAPI)
    const id = typeof markdowncontentAPI === 'number' ? markdowncontentAPI : markdowncontentAPI.ID
    const url = `${this.markdowncontentsUrl}/${id}`;
    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.put<MarkdownContentAPI>(url, markdowncontentAPI, httpOptions).pipe(
      tap(_ => {
      }),
      catchError(this.handleError<MarkdownContentAPI>('updateMarkdownContent'))
    );
  }

  /** PUT: update the markdowncontentdb on the server */
  update(markdowncontentdb: MarkdownContentAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<MarkdownContentAPI> {
    return this.updateMarkdownContent(markdowncontentdb, GONG__StackPath, frontRepo)
  }
  updateMarkdownContent(markdowncontentdb: MarkdownContentAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<MarkdownContentAPI> {
    const id = typeof markdowncontentdb === 'number' ? markdowncontentdb : markdowncontentdb.ID;
    const url = `${this.markdowncontentsUrl}/${id}`;


    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.put<MarkdownContentAPI>(url, markdowncontentdb, httpOptions).pipe(
      tap(_ => {
        // this.log(`updated markdowncontentdb id=${markdowncontentdb.ID}`)
      }),
      catchError(this.handleError<MarkdownContentAPI>('updateMarkdownContent'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation in MarkdownContentService', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error("MarkdownContentService" + error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {
    console.log(message)
  }
}
