// generated by gong
import { Component, OnInit, AfterViewInit, ViewChild, Inject, Optional } from '@angular/core';
import { BehaviorSubject } from 'rxjs'
import { MatSort } from '@angular/material/sort';
import { MatPaginator } from '@angular/material/paginator';
import { MatTableDataSource } from '@angular/material/table';
import { MatButton } from '@angular/material/button'

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData, FrontRepoService, FrontRepo, SelectionMode } from '../front-repo.service'
import { NullInt64 } from '../null-int64'
import { SelectionModel } from '@angular/cdk/collections';

const allowMultiSelect = true;

import { Router, RouterState } from '@angular/router';
import { DummyDataDB } from '../dummydata-db'
import { DummyDataService } from '../dummydata.service'

// insertion point for additional imports

// TableComponent is initilizaed from different routes
// TableComponentMode detail different cases 
enum TableComponentMode {
  DISPLAY_MODE,
  ONE_MANY_ASSOCIATION_MODE,
  MANY_MANY_ASSOCIATION_MODE,
}

// generated table component
@Component({
  selector: 'app-dummydatastable',
  templateUrl: './dummydatas-table.component.html',
  styleUrls: ['./dummydatas-table.component.css'],
})
export class DummyDatasTableComponent implements OnInit {

  // mode at invocation
  mode: TableComponentMode = TableComponentMode.DISPLAY_MODE

  // used if the component is called as a selection component of DummyData instances
  selection: SelectionModel<DummyDataDB> = new (SelectionModel)
  initialSelection = new Array<DummyDataDB>()

  // the data source for the table
  dummydatas: DummyDataDB[] = []
  matTableDataSource: MatTableDataSource<DummyDataDB> = new (MatTableDataSource)

  // front repo, that will be referenced by this.dummydatas
  frontRepo: FrontRepo = new (FrontRepo)

  // displayedColumns is referenced by the MatTable component for specify what columns
  // have to be displayed and in what order
  displayedColumns: string[];

  // for sorting & pagination
  @ViewChild(MatSort)
  sort: MatSort | undefined
  @ViewChild(MatPaginator)
  paginator: MatPaginator | undefined;

  ngAfterViewInit() {

    // enable sorting on all fields (including pointers and reverse pointer)
    this.matTableDataSource.sortingDataAccessor = (dummydataDB: DummyDataDB, property: string) => {
      switch (property) {
        case 'ID':
          return dummydataDB.ID

        // insertion point for specific sorting accessor
        case 'Name':
          return dummydataDB.Name;

        case 'DummyString':
          return dummydataDB.DummyString;

        case 'DummyInt':
          return dummydataDB.DummyInt;

        case 'DummyFloat':
          return dummydataDB.DummyFloat;

        case 'DummyBool':
          return dummydataDB.DummyBool?"true":"false";

        case 'DummyTime':
          return dummydataDB.DummyTime.getDate();

        case 'DummyDuration':
          return dummydataDB.DummyDuration;

        case 'DummyPointerToGongStruct':
          return (dummydataDB.DummyPointerToGongStruct ? dummydataDB.DummyPointerToGongStruct.Name : '');

        default:
          console.assert(false, "Unknown field")
          return "";
      }
    };

    // enable filtering on all fields (including pointers and reverse pointer, which is not done by default)
    this.matTableDataSource.filterPredicate = (dummydataDB: DummyDataDB, filter: string) => {

      // filtering is based on finding a lower case filter into a concatenated string
      // the dummydataDB properties
      let mergedContent = ""

      // insertion point for merging of fields
      mergedContent += dummydataDB.Name.toLowerCase()
      mergedContent += dummydataDB.DummyString.toLowerCase()
      mergedContent += dummydataDB.DummyInt.toString()
      mergedContent += dummydataDB.DummyFloat.toString()
      if (dummydataDB.DummyPointerToGongStruct) {
        mergedContent += dummydataDB.DummyPointerToGongStruct.Name.toLowerCase()
      }

      let isSelected = mergedContent.includes(filter.toLowerCase())
      return isSelected
    };

    this.matTableDataSource.sort = this.sort!
    this.matTableDataSource.paginator = this.paginator!
  }

  applyFilter(event: Event) {
    const filterValue = (event.target as HTMLInputElement).value;
    this.matTableDataSource.filter = filterValue.trim().toLowerCase();
  }

  constructor(
    private dummydataService: DummyDataService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of dummydata instances
    public dialogRef: MatDialogRef<DummyDatasTableComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {

    // compute mode
    if (dialogData == undefined) {
      this.mode = TableComponentMode.DISPLAY_MODE
    } else {
      switch (dialogData.SelectionMode) {
        case SelectionMode.ONE_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.ONE_MANY_ASSOCIATION_MODE
          break
        case SelectionMode.MANY_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.MANY_MANY_ASSOCIATION_MODE
          break
        default:
      }
    }

    // observable for changes in structs
    this.dummydataService.DummyDataServiceChanged.subscribe(
      message => {
        if (message == "post" || message == "update" || message == "delete") {
          this.getDummyDatas()
        }
      }
    )
    if (this.mode == TableComponentMode.DISPLAY_MODE) {
      this.displayedColumns = ['ID', 'Edit', 'Delete', // insertion point for columns to display
        "Name",
        "DummyString",
        "DummyInt",
        "DummyFloat",
        "DummyBool",
        "DummyTime",
        "DummyDuration",
        "DummyPointerToGongStruct",
      ]
    } else {
      this.displayedColumns = ['select', 'ID', // insertion point for columns to display
        "Name",
        "DummyString",
        "DummyInt",
        "DummyFloat",
        "DummyBool",
        "DummyTime",
        "DummyDuration",
        "DummyPointerToGongStruct",
      ]
      this.selection = new SelectionModel<DummyDataDB>(allowMultiSelect, this.initialSelection);
    }

  }

  ngOnInit(): void {
    this.getDummyDatas()
    this.matTableDataSource = new MatTableDataSource(this.dummydatas)
  }

  getDummyDatas(): void {
    this.frontRepoService.pull().subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        this.dummydatas = this.frontRepo.DummyDatas_array;

        // insertion point for time duration Recoveries
        // compute strings for durations
        for (let dummydata of this.dummydatas) {
          dummydata.DummyDuration_string =
            Math.floor(dummydata.DummyDuration / (3600 * 1000 * 1000 * 1000)) + "H " +
            Math.floor(dummydata.DummyDuration % (3600 * 1000 * 1000 * 1000) / (60 * 1000 * 1000 * 1000)) + "M " +
            dummydata.DummyDuration % (60 * 1000 * 1000 * 1000) / (1000 * 1000 * 1000) + "S"
        }
        // insertion point for enum int Recoveries
        
        // in case the component is called as a selection component
        if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {
          for (let dummydata of this.dummydatas) {
            let ID = this.dialogData.ID
            let revPointer = dummydata[this.dialogData.ReversePointer as keyof DummyDataDB] as unknown as NullInt64
            if (revPointer.Int64 == ID) {
              this.initialSelection.push(dummydata)
            }
            this.selection = new SelectionModel<DummyDataDB>(allowMultiSelect, this.initialSelection);
          }
        }

        if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

          let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s" as keyof FrontRepo] as Map<number, DummyDataDB>
          let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)!

          let sourceField = sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]! as unknown as DummyDataDB[]
          for (let associationInstance of sourceField) {
            let dummydata = associationInstance[this.dialogData.IntermediateStructField as keyof typeof associationInstance] as unknown as DummyDataDB
            this.initialSelection.push(dummydata)
          }

          this.selection = new SelectionModel<DummyDataDB>(allowMultiSelect, this.initialSelection);
        }

        // update the mat table data source
        this.matTableDataSource.data = this.dummydatas
      }
    )
  }

  // newDummyData initiate a new dummydata
  // create a new DummyData objet
  newDummyData() {
  }

  deleteDummyData(dummydataID: number, dummydata: DummyDataDB) {
    // list of dummydatas is truncated of dummydata before the delete
    this.dummydatas = this.dummydatas.filter(h => h !== dummydata);

    this.dummydataService.deleteDummyData(dummydataID).subscribe(
      dummydata => {
        this.dummydataService.DummyDataServiceChanged.next("delete")
      }
    );
  }

  editDummyData(dummydataID: number, dummydata: DummyDataDB) {

  }

  // display dummydata in router
  displayDummyDataInRouter(dummydataID: number) {
    this.router.navigate(["github_com_fullstack_lang_gongmarkdown_go-" + "dummydata-display", dummydataID])
  }

  // set editor outlet
  setEditorRouterOutlet(dummydataID: number) {
    this.router.navigate([{
      outlets: {
        github_com_fullstack_lang_gongmarkdown_go_editor: ["github_com_fullstack_lang_gongmarkdown_go-" + "dummydata-detail", dummydataID]
      }
    }]);
  }

  // set presentation outlet
  setPresentationRouterOutlet(dummydataID: number) {
    this.router.navigate([{
      outlets: {
        github_com_fullstack_lang_gongmarkdown_go_presentation: ["github_com_fullstack_lang_gongmarkdown_go-" + "dummydata-presentation", dummydataID]
      }
    }]);
  }

  /** Whether the number of selected elements matches the total number of rows. */
  isAllSelected() {
    const numSelected = this.selection.selected.length;
    const numRows = this.dummydatas.length;
    return numSelected === numRows;
  }

  /** Selects all rows if they are not all selected; otherwise clear selection. */
  masterToggle() {
    this.isAllSelected() ?
      this.selection.clear() :
      this.dummydatas.forEach(row => this.selection.select(row));
  }

  save() {

    if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {

      let toUpdate = new Set<DummyDataDB>()

      // reset all initial selection of dummydata that belong to dummydata
      for (let dummydata of this.initialSelection) {
        let index = dummydata[this.dialogData.ReversePointer as keyof DummyDataDB] as unknown as NullInt64
        index.Int64 = 0
        index.Valid = true
        toUpdate.add(dummydata)

      }

      // from selection, set dummydata that belong to dummydata
      for (let dummydata of this.selection.selected) {
        let ID = this.dialogData.ID as number
        let reversePointer = dummydata[this.dialogData.ReversePointer as keyof DummyDataDB] as unknown as NullInt64
        reversePointer.Int64 = ID
        reversePointer.Valid = true
        toUpdate.add(dummydata)
      }


      // update all dummydata (only update selection & initial selection)
      for (let dummydata of toUpdate) {
        this.dummydataService.updateDummyData(dummydata)
          .subscribe(dummydata => {
            this.dummydataService.DummyDataServiceChanged.next("update")
          });
      }
    }

    if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

      // get the source instance via the map of instances in the front repo
      let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s" as keyof FrontRepo] as Map<number, DummyDataDB>
      let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)!

      // First, parse all instance of the association struct and remove the instance
      // that have unselect
      let unselectedDummyData = new Set<number>()
      for (let dummydata of this.initialSelection) {
        if (this.selection.selected.includes(dummydata)) {
          // console.log("dummydata " + dummydata.Name + " is still selected")
        } else {
          console.log("dummydata " + dummydata.Name + " has been unselected")
          unselectedDummyData.add(dummydata.ID)
          console.log("is unselected " + unselectedDummyData.has(dummydata.ID))
        }
      }

      // delete the association instance
      let associationInstance = sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]
      let dummydata = associationInstance![this.dialogData.IntermediateStructField as keyof typeof associationInstance] as unknown as DummyDataDB
      if (unselectedDummyData.has(dummydata.ID)) {
        this.frontRepoService.deleteService(this.dialogData.IntermediateStruct, associationInstance)


      }

      // is the source array is empty create it
      if (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance] == undefined) {
        (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance] as unknown as Array<DummyDataDB>) = new Array<DummyDataDB>()
      }

      // second, parse all instance of the selected
      if (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]) {
        this.selection.selected.forEach(
          dummydata => {
            if (!this.initialSelection.includes(dummydata)) {
              // console.log("dummydata " + dummydata.Name + " has been added to the selection")

              let associationInstance = {
                Name: sourceInstance["Name"] + "-" + dummydata.Name,
              }

              let index = associationInstance[this.dialogData.IntermediateStructField + "ID" as keyof typeof associationInstance] as unknown as NullInt64
              index.Int64 = dummydata.ID
              index.Valid = true

              let indexDB = associationInstance[this.dialogData.IntermediateStructField + "DBID" as keyof typeof associationInstance] as unknown as NullInt64
              indexDB.Int64 = dummydata.ID
              index.Valid = true

              this.frontRepoService.postService(this.dialogData.IntermediateStruct, associationInstance)

            } else {
              // console.log("dummydata " + dummydata.Name + " is still selected")
            }
          }
        )
      }

      // this.selection = new SelectionModel<DummyDataDB>(allowMultiSelect, this.initialSelection);
    }

    // why pizza ?
    this.dialogRef.close('Pizza!');
  }
}
