// generated by ModelGongFileTemplate
package models

import (
	"fmt"
	"log"
	"os"
	"path"
	"regexp"
	"sort"
	"strings"
)

// swagger:ignore
type __void struct{}

// needed for creating set of instances in the stage
var __member __void

// StageStruct enables storage of staged instances
// swagger:ignore
type StageStruct struct { // insertion point for definition of arrays registering instances
	MarkdownContents           map[*MarkdownContent]struct{}
	MarkdownContents_mapString map[string]*MarkdownContent

	Paragraphs           map[*Paragraph]struct{}
	Paragraphs_mapString map[string]*Paragraph

	AllModelsStructCreateCallback AllModelsStructCreateInterface

	AllModelsStructDeleteCallback AllModelsStructDeleteInterface

	BackRepo BackRepoInterface

	// if set will be called before each commit to the back repo
	OnInitCommitCallback          OnInitCommitInterface
	OnInitCommitFromFrontCallback OnInitCommitInterface
	OnInitCommitFromBackCallback  OnInitCommitInterface

	// store the number of instance per gongstruct
	Map_GongStructName_InstancesNb map[string]int
}

type OnInitCommitInterface interface {
	BeforeCommit(stage *StageStruct)
}

type BackRepoInterface interface {
	Commit(stage *StageStruct)
	Checkout(stage *StageStruct)
	Backup(stage *StageStruct, dirPath string)
	Restore(stage *StageStruct, dirPath string)
	BackupXL(stage *StageStruct, dirPath string)
	RestoreXL(stage *StageStruct, dirPath string)
	// insertion point for Commit and Checkout signatures
	CommitMarkdownContent(markdowncontent *MarkdownContent)
	CheckoutMarkdownContent(markdowncontent *MarkdownContent)
	CommitParagraph(paragraph *Paragraph)
	CheckoutParagraph(paragraph *Paragraph)
	GetLastCommitFromBackNb() uint
	GetLastPushFromFrontNb() uint
}

// swagger:ignore instructs the gong compiler (gongc) to avoid this particular struct
var Stage StageStruct = StageStruct{ // insertion point for array initiatialisation
	MarkdownContents:           make(map[*MarkdownContent]struct{}),
	MarkdownContents_mapString: make(map[string]*MarkdownContent),

	Paragraphs:           make(map[*Paragraph]struct{}),
	Paragraphs_mapString: make(map[string]*Paragraph),

	// end of insertion point
	Map_GongStructName_InstancesNb: make(map[string]int),
}

func (stage *StageStruct) Commit() {
	if stage.BackRepo != nil {
		stage.BackRepo.Commit(stage)
	}

	// insertion point for computing the map of number of instances per gongstruct
	stage.Map_GongStructName_InstancesNb["MarkdownContent"] = len(stage.MarkdownContents)
	stage.Map_GongStructName_InstancesNb["Paragraph"] = len(stage.Paragraphs)

}

func (stage *StageStruct) Checkout() {
	if stage.BackRepo != nil {
		stage.BackRepo.Checkout(stage)
	}
}

// backup generates backup files in the dirPath
func (stage *StageStruct) Backup(dirPath string) {
	if stage.BackRepo != nil {
		stage.BackRepo.Backup(stage, dirPath)
	}
}

// Restore resets Stage & BackRepo and restores their content from the restore files in dirPath
func (stage *StageStruct) Restore(dirPath string) {
	if stage.BackRepo != nil {
		stage.BackRepo.Restore(stage, dirPath)
	}
}

// backup generates backup files in the dirPath
func (stage *StageStruct) BackupXL(dirPath string) {
	if stage.BackRepo != nil {
		stage.BackRepo.BackupXL(stage, dirPath)
	}
}

// Restore resets Stage & BackRepo and restores their content from the restore files in dirPath
func (stage *StageStruct) RestoreXL(dirPath string) {
	if stage.BackRepo != nil {
		stage.BackRepo.RestoreXL(stage, dirPath)
	}
}

// insertion point for cumulative sub template with model space calls
func (stage *StageStruct) getMarkdownContentOrderedStructWithNameField() []*MarkdownContent {
	// have alphabetical order generation
	markdowncontentOrdered := []*MarkdownContent{}
	for markdowncontent := range stage.MarkdownContents {
		markdowncontentOrdered = append(markdowncontentOrdered, markdowncontent)
	}
	sort.Slice(markdowncontentOrdered[:], func(i, j int) bool {
		return markdowncontentOrdered[i].Name < markdowncontentOrdered[j].Name
	})
	return markdowncontentOrdered
}

// Stage puts markdowncontent to the model stage
func (markdowncontent *MarkdownContent) Stage() *MarkdownContent {
	Stage.MarkdownContents[markdowncontent] = __member
	Stage.MarkdownContents_mapString[markdowncontent.Name] = markdowncontent

	return markdowncontent
}

// Unstage removes markdowncontent off the model stage
func (markdowncontent *MarkdownContent) Unstage() *MarkdownContent {
	delete(Stage.MarkdownContents, markdowncontent)
	delete(Stage.MarkdownContents_mapString, markdowncontent.Name)
	return markdowncontent
}

// commit markdowncontent to the back repo (if it is already staged)
func (markdowncontent *MarkdownContent) Commit() *MarkdownContent {
	if _, ok := Stage.MarkdownContents[markdowncontent]; ok {
		if Stage.BackRepo != nil {
			Stage.BackRepo.CommitMarkdownContent(markdowncontent)
		}
	}
	return markdowncontent
}

// Checkout markdowncontent to the back repo (if it is already staged)
func (markdowncontent *MarkdownContent) Checkout() *MarkdownContent {
	if _, ok := Stage.MarkdownContents[markdowncontent]; ok {
		if Stage.BackRepo != nil {
			Stage.BackRepo.CheckoutMarkdownContent(markdowncontent)
		}
	}
	return markdowncontent
}

//
// Legacy, to be deleted
//

// StageCopy appends a copy of markdowncontent to the model stage
func (markdowncontent *MarkdownContent) StageCopy() *MarkdownContent {
	_markdowncontent := new(MarkdownContent)
	*_markdowncontent = *markdowncontent
	_markdowncontent.Stage()
	return _markdowncontent
}

// StageAndCommit appends markdowncontent to the model stage and commit to the orm repo
func (markdowncontent *MarkdownContent) StageAndCommit() *MarkdownContent {
	markdowncontent.Stage()
	if Stage.AllModelsStructCreateCallback != nil {
		Stage.AllModelsStructCreateCallback.CreateORMMarkdownContent(markdowncontent)
	}
	return markdowncontent
}

// DeleteStageAndCommit appends markdowncontent to the model stage and commit to the orm repo
func (markdowncontent *MarkdownContent) DeleteStageAndCommit() *MarkdownContent {
	markdowncontent.Unstage()
	DeleteORMMarkdownContent(markdowncontent)
	return markdowncontent
}

// StageCopyAndCommit appends a copy of markdowncontent to the model stage and commit to the orm repo
func (markdowncontent *MarkdownContent) StageCopyAndCommit() *MarkdownContent {
	_markdowncontent := new(MarkdownContent)
	*_markdowncontent = *markdowncontent
	_markdowncontent.Stage()
	if Stage.AllModelsStructCreateCallback != nil {
		Stage.AllModelsStructCreateCallback.CreateORMMarkdownContent(markdowncontent)
	}
	return _markdowncontent
}

// CreateORMMarkdownContent enables dynamic staging of a MarkdownContent instance
func CreateORMMarkdownContent(markdowncontent *MarkdownContent) {
	markdowncontent.Stage()
	if Stage.AllModelsStructCreateCallback != nil {
		Stage.AllModelsStructCreateCallback.CreateORMMarkdownContent(markdowncontent)
	}
}

// DeleteORMMarkdownContent enables dynamic staging of a MarkdownContent instance
func DeleteORMMarkdownContent(markdowncontent *MarkdownContent) {
	markdowncontent.Unstage()
	if Stage.AllModelsStructDeleteCallback != nil {
		Stage.AllModelsStructDeleteCallback.DeleteORMMarkdownContent(markdowncontent)
	}
}

func (stage *StageStruct) getParagraphOrderedStructWithNameField() []*Paragraph {
	// have alphabetical order generation
	paragraphOrdered := []*Paragraph{}
	for paragraph := range stage.Paragraphs {
		paragraphOrdered = append(paragraphOrdered, paragraph)
	}
	sort.Slice(paragraphOrdered[:], func(i, j int) bool {
		return paragraphOrdered[i].Name < paragraphOrdered[j].Name
	})
	return paragraphOrdered
}

// Stage puts paragraph to the model stage
func (paragraph *Paragraph) Stage() *Paragraph {
	Stage.Paragraphs[paragraph] = __member
	Stage.Paragraphs_mapString[paragraph.Name] = paragraph

	return paragraph
}

// Unstage removes paragraph off the model stage
func (paragraph *Paragraph) Unstage() *Paragraph {
	delete(Stage.Paragraphs, paragraph)
	delete(Stage.Paragraphs_mapString, paragraph.Name)
	return paragraph
}

// commit paragraph to the back repo (if it is already staged)
func (paragraph *Paragraph) Commit() *Paragraph {
	if _, ok := Stage.Paragraphs[paragraph]; ok {
		if Stage.BackRepo != nil {
			Stage.BackRepo.CommitParagraph(paragraph)
		}
	}
	return paragraph
}

// Checkout paragraph to the back repo (if it is already staged)
func (paragraph *Paragraph) Checkout() *Paragraph {
	if _, ok := Stage.Paragraphs[paragraph]; ok {
		if Stage.BackRepo != nil {
			Stage.BackRepo.CheckoutParagraph(paragraph)
		}
	}
	return paragraph
}

//
// Legacy, to be deleted
//

// StageCopy appends a copy of paragraph to the model stage
func (paragraph *Paragraph) StageCopy() *Paragraph {
	_paragraph := new(Paragraph)
	*_paragraph = *paragraph
	_paragraph.Stage()
	return _paragraph
}

// StageAndCommit appends paragraph to the model stage and commit to the orm repo
func (paragraph *Paragraph) StageAndCommit() *Paragraph {
	paragraph.Stage()
	if Stage.AllModelsStructCreateCallback != nil {
		Stage.AllModelsStructCreateCallback.CreateORMParagraph(paragraph)
	}
	return paragraph
}

// DeleteStageAndCommit appends paragraph to the model stage and commit to the orm repo
func (paragraph *Paragraph) DeleteStageAndCommit() *Paragraph {
	paragraph.Unstage()
	DeleteORMParagraph(paragraph)
	return paragraph
}

// StageCopyAndCommit appends a copy of paragraph to the model stage and commit to the orm repo
func (paragraph *Paragraph) StageCopyAndCommit() *Paragraph {
	_paragraph := new(Paragraph)
	*_paragraph = *paragraph
	_paragraph.Stage()
	if Stage.AllModelsStructCreateCallback != nil {
		Stage.AllModelsStructCreateCallback.CreateORMParagraph(paragraph)
	}
	return _paragraph
}

// CreateORMParagraph enables dynamic staging of a Paragraph instance
func CreateORMParagraph(paragraph *Paragraph) {
	paragraph.Stage()
	if Stage.AllModelsStructCreateCallback != nil {
		Stage.AllModelsStructCreateCallback.CreateORMParagraph(paragraph)
	}
}

// DeleteORMParagraph enables dynamic staging of a Paragraph instance
func DeleteORMParagraph(paragraph *Paragraph) {
	paragraph.Unstage()
	if Stage.AllModelsStructDeleteCallback != nil {
		Stage.AllModelsStructDeleteCallback.DeleteORMParagraph(paragraph)
	}
}

// swagger:ignore
type AllModelsStructCreateInterface interface { // insertion point for Callbacks on creation
	CreateORMMarkdownContent(MarkdownContent *MarkdownContent)
	CreateORMParagraph(Paragraph *Paragraph)
}

type AllModelsStructDeleteInterface interface { // insertion point for Callbacks on deletion
	DeleteORMMarkdownContent(MarkdownContent *MarkdownContent)
	DeleteORMParagraph(Paragraph *Paragraph)
}

func (stage *StageStruct) Reset() { // insertion point for array reset
	stage.MarkdownContents = make(map[*MarkdownContent]struct{})
	stage.MarkdownContents_mapString = make(map[string]*MarkdownContent)

	stage.Paragraphs = make(map[*Paragraph]struct{})
	stage.Paragraphs_mapString = make(map[string]*Paragraph)

}

func (stage *StageStruct) Nil() { // insertion point for array nil
	stage.MarkdownContents = nil
	stage.MarkdownContents_mapString = nil

	stage.Paragraphs = nil
	stage.Paragraphs_mapString = nil

}

const marshallRes = `package {{PackageName}}

import (
	"time"

	"{{ModelsPackageName}}"
)

func init() {
	var __Dummy_time_variable time.Time
	_ = __Dummy_time_variable
	InjectionGateway["{{databaseName}}"] = {{databaseName}}Injection
}

// {{databaseName}}Injection will stage objects of database "{{databaseName}}"
func {{databaseName}}Injection() {

	// Declaration of instances to stage{{Identifiers}}

	// Setup of values{{ValueInitializers}}

	// Setup of pointers{{PointersInitializers}}
}

`

const IdentifiersDecls = `
	{{Identifier}} := (&models.{{GeneratedStructName}}{Name: "{{GeneratedFieldNameValue}}"}).Stage()`

const StringInitStatement = `
	{{Identifier}}.{{GeneratedFieldName}} = ` + "`" + `{{GeneratedFieldNameValue}}` + "`"

const StringEnumInitStatement = `
	{{Identifier}}.{{GeneratedFieldName}} = {{GeneratedFieldNameValue}}`

const NumberInitStatement = `
	{{Identifier}}.{{GeneratedFieldName}} = {{GeneratedFieldNameValue}}`

const PointerFieldInitStatement = `
	{{Identifier}}.{{GeneratedFieldName}} = {{GeneratedFieldNameValue}}`

const SliceOfPointersFieldInitStatement = `
	{{Identifier}}.{{GeneratedFieldName}} = append({{Identifier}}.{{GeneratedFieldName}}, {{GeneratedFieldNameValue}})`

const TimeInitStatement = `
	{{Identifier}}.{{GeneratedFieldName}}, _ = time.Parse("2006-01-02 15:04:05.999999999 -0700 MST", "{{GeneratedFieldNameValue}}")`

// Marshall marshall the stage content into the file as an instanciation into a stage
func (stage *StageStruct) Marshall(file *os.File, modelsPackageName, packageName string) {

	name := file.Name()

	if !strings.HasSuffix(name, ".go") {
		log.Fatalln(name + " is not a go filename")
	}

	log.Println("filename of marshall output  is " + name)

	res := marshallRes
	res = strings.ReplaceAll(res, "{{databaseName}}", strings.ReplaceAll(path.Base(name), ".go", ""))
	res = strings.ReplaceAll(res, "{{PackageName}}", packageName)
	res = strings.ReplaceAll(res, "{{ModelsPackageName}}", modelsPackageName)

	// map of identifiers
	// var StageMapDstructIds map[*Dstruct]string
	identifiersDecl := ""
	initializerStatements := ""
	pointersInitializesStatements := ""

	id := ""
	decl := ""
	setValueField := ""

	// insertion initialization of objects to stage
	map_MarkdownContent_Identifiers := make(map[*MarkdownContent]string)
	_ = map_MarkdownContent_Identifiers

	markdowncontentOrdered := []*MarkdownContent{}
	for markdowncontent := range stage.MarkdownContents {
		markdowncontentOrdered = append(markdowncontentOrdered, markdowncontent)
	}
	sort.Slice(markdowncontentOrdered[:], func(i, j int) bool {
		return markdowncontentOrdered[i].Name < markdowncontentOrdered[j].Name
	})
	identifiersDecl += fmt.Sprintf("\n\n	// Declarations of staged instances of MarkdownContent")
	for idx, markdowncontent := range markdowncontentOrdered {

		id = generatesIdentifier("MarkdownContent", idx, markdowncontent.Name)
		map_MarkdownContent_Identifiers[markdowncontent] = id

		decl = IdentifiersDecls
		decl = strings.ReplaceAll(decl, "{{Identifier}}", id)
		decl = strings.ReplaceAll(decl, "{{GeneratedStructName}}", "MarkdownContent")
		decl = strings.ReplaceAll(decl, "{{GeneratedFieldNameValue}}", markdowncontent.Name)
		identifiersDecl += decl

		initializerStatements += fmt.Sprintf("\n\n	// MarkdownContent %s values setup", markdowncontent.Name)
		// Initialisation of values
		setValueField = StringInitStatement
		setValueField = strings.ReplaceAll(setValueField, "{{Identifier}}", id)
		setValueField = strings.ReplaceAll(setValueField, "{{GeneratedFieldName}}", "Name")
		setValueField = strings.ReplaceAll(setValueField, "{{GeneratedFieldNameValue}}", string(markdowncontent.Name))
		initializerStatements += setValueField

		setValueField = StringInitStatement
		setValueField = strings.ReplaceAll(setValueField, "{{Identifier}}", id)
		setValueField = strings.ReplaceAll(setValueField, "{{GeneratedFieldName}}", "Content")
		setValueField = strings.ReplaceAll(setValueField, "{{GeneratedFieldNameValue}}", string(markdowncontent.Content))
		initializerStatements += setValueField

	}

	map_Paragraph_Identifiers := make(map[*Paragraph]string)
	_ = map_Paragraph_Identifiers

	paragraphOrdered := []*Paragraph{}
	for paragraph := range stage.Paragraphs {
		paragraphOrdered = append(paragraphOrdered, paragraph)
	}
	sort.Slice(paragraphOrdered[:], func(i, j int) bool {
		return paragraphOrdered[i].Name < paragraphOrdered[j].Name
	})
	identifiersDecl += fmt.Sprintf("\n\n	// Declarations of staged instances of Paragraph")
	for idx, paragraph := range paragraphOrdered {

		id = generatesIdentifier("Paragraph", idx, paragraph.Name)
		map_Paragraph_Identifiers[paragraph] = id

		decl = IdentifiersDecls
		decl = strings.ReplaceAll(decl, "{{Identifier}}", id)
		decl = strings.ReplaceAll(decl, "{{GeneratedStructName}}", "Paragraph")
		decl = strings.ReplaceAll(decl, "{{GeneratedFieldNameValue}}", paragraph.Name)
		identifiersDecl += decl

		initializerStatements += fmt.Sprintf("\n\n	// Paragraph %s values setup", paragraph.Name)
		// Initialisation of values
		setValueField = StringInitStatement
		setValueField = strings.ReplaceAll(setValueField, "{{Identifier}}", id)
		setValueField = strings.ReplaceAll(setValueField, "{{GeneratedFieldName}}", "Name")
		setValueField = strings.ReplaceAll(setValueField, "{{GeneratedFieldNameValue}}", string(paragraph.Name))
		initializerStatements += setValueField

		setValueField = StringInitStatement
		setValueField = strings.ReplaceAll(setValueField, "{{Identifier}}", id)
		setValueField = strings.ReplaceAll(setValueField, "{{GeneratedFieldName}}", "Content")
		setValueField = strings.ReplaceAll(setValueField, "{{GeneratedFieldNameValue}}", string(paragraph.Content))
		initializerStatements += setValueField

	}

	// insertion initialization of objects to stage
	for idx, markdowncontent := range markdowncontentOrdered {
		var setPointerField string
		_ = setPointerField

		id = generatesIdentifier("MarkdownContent", idx, markdowncontent.Name)
		map_MarkdownContent_Identifiers[markdowncontent] = id

		// Initialisation of values
	}

	for idx, paragraph := range paragraphOrdered {
		var setPointerField string
		_ = setPointerField

		id = generatesIdentifier("Paragraph", idx, paragraph.Name)
		map_Paragraph_Identifiers[paragraph] = id

		// Initialisation of values
	}

	res = strings.ReplaceAll(res, "{{Identifiers}}", identifiersDecl)
	res = strings.ReplaceAll(res, "{{ValueInitializers}}", initializerStatements)
	res = strings.ReplaceAll(res, "{{PointersInitializers}}", pointersInitializesStatements)

	fmt.Fprintln(file, res)
}

// unique identifier per struct
func generatesIdentifier(gongStructName string, idx int, instanceName string) (identifier string) {

	identifier = instanceName
	// Make a Regex to say we only want letters and numbers
	reg, err := regexp.Compile("[^a-zA-Z0-9]+")
	if err != nil {
		log.Fatal(err)
	}
	processedString := reg.ReplaceAllString(instanceName, "_")

	identifier = fmt.Sprintf("__%s__%06d_%s", gongStructName, idx, processedString)

	return
}

// insertion point of enum utility functions
