// generated by gong
import { Component, OnInit, AfterViewInit, ViewChild, Inject, Optional } from '@angular/core';
import { BehaviorSubject } from 'rxjs'
import { MatSort } from '@angular/material/sort';
import { MatPaginator } from '@angular/material/paginator';
import { MatTableDataSource } from '@angular/material/table';
import { MatButton } from '@angular/material/button'

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData, FrontRepoService, FrontRepo, SelectionMode } from '../front-repo.service'
import { NullInt64 } from '../null-int64'
import { SelectionModel } from '@angular/cdk/collections';

const allowMultiSelect = true;

import { Router, RouterState } from '@angular/router';
import { MarkdownContentDB } from '../markdowncontent-db'
import { MarkdownContentService } from '../markdowncontent.service'

// insertion point for additional imports

// TableComponent is initilizaed from different routes
// TableComponentMode detail different cases 
enum TableComponentMode {
  DISPLAY_MODE,
  ONE_MANY_ASSOCIATION_MODE,
  MANY_MANY_ASSOCIATION_MODE,
}

// generated table component
@Component({
  selector: 'app-markdowncontentstable',
  templateUrl: './markdowncontents-table.component.html',
  styleUrls: ['./markdowncontents-table.component.css'],
})
export class MarkdownContentsTableComponent implements OnInit {

  // mode at invocation
  mode: TableComponentMode = TableComponentMode.DISPLAY_MODE

  // used if the component is called as a selection component of MarkdownContent instances
  selection: SelectionModel<MarkdownContentDB> = new (SelectionModel)
  initialSelection = new Array<MarkdownContentDB>()

  // the data source for the table
  markdowncontents: MarkdownContentDB[] = []
  matTableDataSource: MatTableDataSource<MarkdownContentDB> = new (MatTableDataSource)

  // front repo, that will be referenced by this.markdowncontents
  frontRepo: FrontRepo = new (FrontRepo)

  // displayedColumns is referenced by the MatTable component for specify what columns
  // have to be displayed and in what order
  displayedColumns: string[];

  // for sorting & pagination
  @ViewChild(MatSort)
  sort: MatSort | undefined
  @ViewChild(MatPaginator)
  paginator: MatPaginator | undefined;

  ngAfterViewInit() {

    // enable sorting on all fields (including pointers and reverse pointer)
    this.matTableDataSource.sortingDataAccessor = (markdowncontentDB: MarkdownContentDB, property: string) => {
      switch (property) {
        case 'ID':
          return markdowncontentDB.ID

        // insertion point for specific sorting accessor
        case 'Name':
          return markdowncontentDB.Name;

        case 'Content':
          return markdowncontentDB.Content;

        default:
          console.assert(false, "Unknown field")
          return "";
      }
    };

    // enable filtering on all fields (including pointers and reverse pointer, which is not done by default)
    this.matTableDataSource.filterPredicate = (markdowncontentDB: MarkdownContentDB, filter: string) => {

      // filtering is based on finding a lower case filter into a concatenated string
      // the markdowncontentDB properties
      let mergedContent = ""

      // insertion point for merging of fields
      mergedContent += markdowncontentDB.Name.toLowerCase()
      mergedContent += markdowncontentDB.Content.toLowerCase()

      let isSelected = mergedContent.includes(filter.toLowerCase())
      return isSelected
    };

    this.matTableDataSource.sort = this.sort!
    this.matTableDataSource.paginator = this.paginator!
  }

  applyFilter(event: Event) {
    const filterValue = (event.target as HTMLInputElement).value;
    this.matTableDataSource.filter = filterValue.trim().toLowerCase();
  }

  constructor(
    private markdowncontentService: MarkdownContentService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of markdowncontent instances
    public dialogRef: MatDialogRef<MarkdownContentsTableComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {

    // compute mode
    if (dialogData == undefined) {
      this.mode = TableComponentMode.DISPLAY_MODE
    } else {
      switch (dialogData.SelectionMode) {
        case SelectionMode.ONE_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.ONE_MANY_ASSOCIATION_MODE
          break
        case SelectionMode.MANY_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.MANY_MANY_ASSOCIATION_MODE
          break
        default:
      }
    }

    // observable for changes in structs
    this.markdowncontentService.MarkdownContentServiceChanged.subscribe(
      message => {
        if (message == "post" || message == "update" || message == "delete") {
          this.getMarkdownContents()
        }
      }
    )
    if (this.mode == TableComponentMode.DISPLAY_MODE) {
      this.displayedColumns = ['ID', 'Edit', 'Delete', // insertion point for columns to display
        "Name",
        "Content",
      ]
    } else {
      this.displayedColumns = ['select', 'ID', // insertion point for columns to display
        "Name",
        "Content",
      ]
      this.selection = new SelectionModel<MarkdownContentDB>(allowMultiSelect, this.initialSelection);
    }

  }

  ngOnInit(): void {
    this.getMarkdownContents()
    this.matTableDataSource = new MatTableDataSource(this.markdowncontents)
  }

  getMarkdownContents(): void {
    this.frontRepoService.pull().subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        this.markdowncontents = this.frontRepo.MarkdownContents_array;

        // insertion point for time duration Recoveries
        // insertion point for enum int Recoveries
        
        // in case the component is called as a selection component
        if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {
          for (let markdowncontent of this.markdowncontents) {
            let ID = this.dialogData.ID
            let revPointer = markdowncontent[this.dialogData.ReversePointer as keyof MarkdownContentDB] as unknown as NullInt64
            if (revPointer.Int64 == ID) {
              this.initialSelection.push(markdowncontent)
            }
            this.selection = new SelectionModel<MarkdownContentDB>(allowMultiSelect, this.initialSelection);
          }
        }

        if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

          let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s" as keyof FrontRepo] as Map<number, MarkdownContentDB>
          let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)!

          let sourceField = sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]! as unknown as MarkdownContentDB[]
          for (let associationInstance of sourceField) {
            let markdowncontent = associationInstance[this.dialogData.IntermediateStructField as keyof typeof associationInstance] as unknown as MarkdownContentDB
            this.initialSelection.push(markdowncontent)
          }

          this.selection = new SelectionModel<MarkdownContentDB>(allowMultiSelect, this.initialSelection);
        }

        // update the mat table data source
        this.matTableDataSource.data = this.markdowncontents
      }
    )
  }

  // newMarkdownContent initiate a new markdowncontent
  // create a new MarkdownContent objet
  newMarkdownContent() {
  }

  deleteMarkdownContent(markdowncontentID: number, markdowncontent: MarkdownContentDB) {
    // list of markdowncontents is truncated of markdowncontent before the delete
    this.markdowncontents = this.markdowncontents.filter(h => h !== markdowncontent);

    this.markdowncontentService.deleteMarkdownContent(markdowncontentID).subscribe(
      markdowncontent => {
        this.markdowncontentService.MarkdownContentServiceChanged.next("delete")
      }
    );
  }

  editMarkdownContent(markdowncontentID: number, markdowncontent: MarkdownContentDB) {

  }

  // display markdowncontent in router
  displayMarkdownContentInRouter(markdowncontentID: number) {
    this.router.navigate(["gongmarkdown_go-" + "markdowncontent-display", markdowncontentID])
  }

  // set editor outlet
  setEditorRouterOutlet(markdowncontentID: number) {
    this.router.navigate([{
      outlets: {
        gongmarkdown_go_editor: ["gongmarkdown_go-" + "markdowncontent-detail", markdowncontentID]
      }
    }]);
  }

  // set presentation outlet
  setPresentationRouterOutlet(markdowncontentID: number) {
    this.router.navigate([{
      outlets: {
        gongmarkdown_go_presentation: ["gongmarkdown_go-" + "markdowncontent-presentation", markdowncontentID]
      }
    }]);
  }

  /** Whether the number of selected elements matches the total number of rows. */
  isAllSelected() {
    const numSelected = this.selection.selected.length;
    const numRows = this.markdowncontents.length;
    return numSelected === numRows;
  }

  /** Selects all rows if they are not all selected; otherwise clear selection. */
  masterToggle() {
    this.isAllSelected() ?
      this.selection.clear() :
      this.markdowncontents.forEach(row => this.selection.select(row));
  }

  save() {

    if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {

      let toUpdate = new Set<MarkdownContentDB>()

      // reset all initial selection of markdowncontent that belong to markdowncontent
      for (let markdowncontent of this.initialSelection) {
        let index = markdowncontent[this.dialogData.ReversePointer as keyof MarkdownContentDB] as unknown as NullInt64
        index.Int64 = 0
        index.Valid = true
        toUpdate.add(markdowncontent)

      }

      // from selection, set markdowncontent that belong to markdowncontent
      for (let markdowncontent of this.selection.selected) {
        let ID = this.dialogData.ID as number
        let reversePointer = markdowncontent[this.dialogData.ReversePointer as keyof MarkdownContentDB] as unknown as NullInt64
        reversePointer.Int64 = ID
        reversePointer.Valid = true
        toUpdate.add(markdowncontent)
      }


      // update all markdowncontent (only update selection & initial selection)
      for (let markdowncontent of toUpdate) {
        this.markdowncontentService.updateMarkdownContent(markdowncontent)
          .subscribe(markdowncontent => {
            this.markdowncontentService.MarkdownContentServiceChanged.next("update")
          });
      }
    }

    if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

      // get the source instance via the map of instances in the front repo
      let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s" as keyof FrontRepo] as Map<number, MarkdownContentDB>
      let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)!

      // First, parse all instance of the association struct and remove the instance
      // that have unselect
      let unselectedMarkdownContent = new Set<number>()
      for (let markdowncontent of this.initialSelection) {
        if (this.selection.selected.includes(markdowncontent)) {
          // console.log("markdowncontent " + markdowncontent.Name + " is still selected")
        } else {
          console.log("markdowncontent " + markdowncontent.Name + " has been unselected")
          unselectedMarkdownContent.add(markdowncontent.ID)
          console.log("is unselected " + unselectedMarkdownContent.has(markdowncontent.ID))
        }
      }

      // delete the association instance
      let associationInstance = sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]
      let markdowncontent = associationInstance![this.dialogData.IntermediateStructField as keyof typeof associationInstance] as unknown as MarkdownContentDB
      if (unselectedMarkdownContent.has(markdowncontent.ID)) {
        this.frontRepoService.deleteService(this.dialogData.IntermediateStruct, associationInstance)


      }

      // is the source array is empty create it
      if (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance] == undefined) {
        (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance] as unknown as Array<MarkdownContentDB>) = new Array<MarkdownContentDB>()
      }

      // second, parse all instance of the selected
      if (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]) {
        this.selection.selected.forEach(
          markdowncontent => {
            if (!this.initialSelection.includes(markdowncontent)) {
              // console.log("markdowncontent " + markdowncontent.Name + " has been added to the selection")

              let associationInstance = {
                Name: sourceInstance["Name"] + "-" + markdowncontent.Name,
              }

              let index = associationInstance[this.dialogData.IntermediateStructField + "ID" as keyof typeof associationInstance] as unknown as NullInt64
              index.Int64 = markdowncontent.ID
              index.Valid = true

              let indexDB = associationInstance[this.dialogData.IntermediateStructField + "DBID" as keyof typeof associationInstance] as unknown as NullInt64
              indexDB.Int64 = markdowncontent.ID
              index.Valid = true

              this.frontRepoService.postService(this.dialogData.IntermediateStruct, associationInstance)

            } else {
              // console.log("markdowncontent " + markdowncontent.Name + " is still selected")
            }
          }
        )
      }

      // this.selection = new SelectionModel<MarkdownContentDB>(allowMultiSelect, this.initialSelection);
    }

    // why pizza ?
    this.dialogRef.close('Pizza!');
  }
}
