// generated by ng_file_service_ts
import { Injectable, Component, Inject } from '@angular/core';
import { HttpClientModule } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { DOCUMENT, Location } from '@angular/common'

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs';
import { Observable, of } from 'rxjs';
import { catchError, map, tap } from 'rxjs/operators';

import { AnotherDummyDataDB } from './anotherdummydata-db';

// insertion point for imports

@Injectable({
  providedIn: 'root'
})
export class AnotherDummyDataService {

  httpOptions = {
    headers: new HttpHeaders({ 'Content-Type': 'application/json' })
  };

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  AnotherDummyDataServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private anotherdummydatasUrl: string

  constructor(
    private http: HttpClient,
    private location: Location,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
    let origin = this.document.location.origin

    // if debugging with ng, replace 4200 with 8080
    origin = origin.replace("4200", "8080")

    // compute path to the service
    this.anotherdummydatasUrl = origin + '/api/github.com/fullstack-lang/gongmarkdown/go/v1/anotherdummydatas';
  }

  /** GET anotherdummydatas from the server */
  getAnotherDummyDatas(): Observable<AnotherDummyDataDB[]> {
    return this.http.get<AnotherDummyDataDB[]>(this.anotherdummydatasUrl)
      .pipe(
        tap(_ => this.log('fetched anotherdummydatas')),
        catchError(this.handleError<AnotherDummyDataDB[]>('getAnotherDummyDatas', []))
      );
  }

  /** GET anotherdummydata by id. Will 404 if id not found */
  getAnotherDummyData(id: number): Observable<AnotherDummyDataDB> {
    const url = `${this.anotherdummydatasUrl}/${id}`;
    return this.http.get<AnotherDummyDataDB>(url).pipe(
      tap(_ => this.log(`fetched anotherdummydata id=${id}`)),
      catchError(this.handleError<AnotherDummyDataDB>(`getAnotherDummyData id=${id}`))
    );
  }

  //////// Save methods //////////

  /** POST: add a new anotherdummydata to the server */
  postAnotherDummyData(anotherdummydatadb: AnotherDummyDataDB): Observable<AnotherDummyDataDB> {

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)

    return this.http.post<AnotherDummyDataDB>(this.anotherdummydatasUrl, anotherdummydatadb, this.httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        this.log(`posted anotherdummydatadb id=${anotherdummydatadb.ID}`)
      }),
      catchError(this.handleError<AnotherDummyDataDB>('postAnotherDummyData'))
    );
  }

  /** DELETE: delete the anotherdummydatadb from the server */
  deleteAnotherDummyData(anotherdummydatadb: AnotherDummyDataDB | number): Observable<AnotherDummyDataDB> {
    const id = typeof anotherdummydatadb === 'number' ? anotherdummydatadb : anotherdummydatadb.ID;
    const url = `${this.anotherdummydatasUrl}/${id}`;

    return this.http.delete<AnotherDummyDataDB>(url, this.httpOptions).pipe(
      tap(_ => this.log(`deleted anotherdummydatadb id=${id}`)),
      catchError(this.handleError<AnotherDummyDataDB>('deleteAnotherDummyData'))
    );
  }

  /** PUT: update the anotherdummydatadb on the server */
  updateAnotherDummyData(anotherdummydatadb: AnotherDummyDataDB): Observable<AnotherDummyDataDB> {
    const id = typeof anotherdummydatadb === 'number' ? anotherdummydatadb : anotherdummydatadb.ID;
    const url = `${this.anotherdummydatasUrl}/${id}`;

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)

    return this.http.put<AnotherDummyDataDB>(url, anotherdummydatadb, this.httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        this.log(`updated anotherdummydatadb id=${anotherdummydatadb.ID}`)
      }),
      catchError(this.handleError<AnotherDummyDataDB>('updateAnotherDummyData'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error(error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {

  }
}
