// generated by ng_file_service_ts
import { Injectable, Component, Inject } from '@angular/core';
import { HttpClientModule } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { DOCUMENT, Location } from '@angular/common'

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs';
import { Observable, of } from 'rxjs';
import { catchError, map, tap } from 'rxjs/operators';

import { MarkdownContentDB } from './markdowncontent-db';

// insertion point for imports

@Injectable({
  providedIn: 'root'
})
export class MarkdownContentService {

  httpOptions = {
    headers: new HttpHeaders({ 'Content-Type': 'application/json' })
  };

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  MarkdownContentServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private markdowncontentsUrl: string

  constructor(
    private http: HttpClient,
    private location: Location,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
    let origin = this.document.location.origin

    // if debugging with ng, replace 4200 with 8080
    origin = origin.replace("4200", "8080")

    // compute path to the service
    this.markdowncontentsUrl = origin + '/api/gongmarkdown/go/v1/markdowncontents';
  }

  /** GET markdowncontents from the server */
  getMarkdownContents(): Observable<MarkdownContentDB[]> {
    return this.http.get<MarkdownContentDB[]>(this.markdowncontentsUrl)
      .pipe(
        tap(_ => this.log('fetched markdowncontents')),
        catchError(this.handleError<MarkdownContentDB[]>('getMarkdownContents', []))
      );
  }

  /** GET markdowncontent by id. Will 404 if id not found */
  getMarkdownContent(id: number): Observable<MarkdownContentDB> {
    const url = `${this.markdowncontentsUrl}/${id}`;
    return this.http.get<MarkdownContentDB>(url).pipe(
      tap(_ => this.log(`fetched markdowncontent id=${id}`)),
      catchError(this.handleError<MarkdownContentDB>(`getMarkdownContent id=${id}`))
    );
  }

  //////// Save methods //////////

  /** POST: add a new markdowncontent to the server */
  postMarkdownContent(markdowncontentdb: MarkdownContentDB): Observable<MarkdownContentDB> {

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)

    return this.http.post<MarkdownContentDB>(this.markdowncontentsUrl, markdowncontentdb, this.httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        this.log(`posted markdowncontentdb id=${markdowncontentdb.ID}`)
      }),
      catchError(this.handleError<MarkdownContentDB>('postMarkdownContent'))
    );
  }

  /** DELETE: delete the markdowncontentdb from the server */
  deleteMarkdownContent(markdowncontentdb: MarkdownContentDB | number): Observable<MarkdownContentDB> {
    const id = typeof markdowncontentdb === 'number' ? markdowncontentdb : markdowncontentdb.ID;
    const url = `${this.markdowncontentsUrl}/${id}`;

    return this.http.delete<MarkdownContentDB>(url, this.httpOptions).pipe(
      tap(_ => this.log(`deleted markdowncontentdb id=${id}`)),
      catchError(this.handleError<MarkdownContentDB>('deleteMarkdownContent'))
    );
  }

  /** PUT: update the markdowncontentdb on the server */
  updateMarkdownContent(markdowncontentdb: MarkdownContentDB): Observable<MarkdownContentDB> {
    const id = typeof markdowncontentdb === 'number' ? markdowncontentdb : markdowncontentdb.ID;
    const url = `${this.markdowncontentsUrl}/${id}`;

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)

    return this.http.put<MarkdownContentDB>(url, markdowncontentdb, this.httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        this.log(`updated markdowncontentdb id=${markdowncontentdb.ID}`)
      }),
      catchError(this.handleError<MarkdownContentDB>('updateMarkdownContent'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error(error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {

  }
}
