// generated by ng_file_service_ts
import { Injectable, Component, Inject } from '@angular/core';
import { HttpClientModule } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { DOCUMENT, Location } from '@angular/common'

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs';
import { Observable, of } from 'rxjs';
import { catchError, map, tap } from 'rxjs/operators';

import { ParagraphDB } from './paragraph-db';

// insertion point for imports

@Injectable({
  providedIn: 'root'
})
export class ParagraphService {

  httpOptions = {
    headers: new HttpHeaders({ 'Content-Type': 'application/json' })
  };

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  ParagraphServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private paragraphsUrl: string

  constructor(
    private http: HttpClient,
    private location: Location,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
    let origin = this.document.location.origin

    // if debugging with ng, replace 4200 with 8080
    origin = origin.replace("4200", "8080")

    // compute path to the service
    this.paragraphsUrl = origin + '/api/gongmarkdown/go/v1/paragraphs';
  }

  /** GET paragraphs from the server */
  getParagraphs(): Observable<ParagraphDB[]> {
    return this.http.get<ParagraphDB[]>(this.paragraphsUrl)
      .pipe(
        tap(_ => this.log('fetched paragraphs')),
        catchError(this.handleError<ParagraphDB[]>('getParagraphs', []))
      );
  }

  /** GET paragraph by id. Will 404 if id not found */
  getParagraph(id: number): Observable<ParagraphDB> {
    const url = `${this.paragraphsUrl}/${id}`;
    return this.http.get<ParagraphDB>(url).pipe(
      tap(_ => this.log(`fetched paragraph id=${id}`)),
      catchError(this.handleError<ParagraphDB>(`getParagraph id=${id}`))
    );
  }

  //////// Save methods //////////

  /** POST: add a new paragraph to the server */
  postParagraph(paragraphdb: ParagraphDB): Observable<ParagraphDB> {

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)

    return this.http.post<ParagraphDB>(this.paragraphsUrl, paragraphdb, this.httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        this.log(`posted paragraphdb id=${paragraphdb.ID}`)
      }),
      catchError(this.handleError<ParagraphDB>('postParagraph'))
    );
  }

  /** DELETE: delete the paragraphdb from the server */
  deleteParagraph(paragraphdb: ParagraphDB | number): Observable<ParagraphDB> {
    const id = typeof paragraphdb === 'number' ? paragraphdb : paragraphdb.ID;
    const url = `${this.paragraphsUrl}/${id}`;

    return this.http.delete<ParagraphDB>(url, this.httpOptions).pipe(
      tap(_ => this.log(`deleted paragraphdb id=${id}`)),
      catchError(this.handleError<ParagraphDB>('deleteParagraph'))
    );
  }

  /** PUT: update the paragraphdb on the server */
  updateParagraph(paragraphdb: ParagraphDB): Observable<ParagraphDB> {
    const id = typeof paragraphdb === 'number' ? paragraphdb : paragraphdb.ID;
    const url = `${this.paragraphsUrl}/${id}`;

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)

    return this.http.put<ParagraphDB>(url, paragraphdb, this.httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        this.log(`updated paragraphdb id=${paragraphdb.ID}`)
      }),
      catchError(this.handleError<ParagraphDB>('updateParagraph'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error(error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {

  }
}
