// generated by ng_file_service_ts
import { Injectable, Component, Inject } from '@angular/core';
import { HttpClientModule } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { DOCUMENT, Location } from '@angular/common'

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs';
import { Observable, of } from 'rxjs';
import { catchError, map, tap } from 'rxjs/operators';

import { RowDB } from './row-db';

// insertion point for imports
import { ElementDB } from './element-db'

@Injectable({
  providedIn: 'root'
})
export class RowService {

  httpOptions = {
    headers: new HttpHeaders({ 'Content-Type': 'application/json' })
  };

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  RowServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private rowsUrl: string

  constructor(
    private http: HttpClient,
    private location: Location,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
    let origin = this.document.location.origin

    // if debugging with ng, replace 4200 with 8080
    origin = origin.replace("4200", "8080")

    // compute path to the service
    this.rowsUrl = origin + '/api/github.com/fullstack-lang/gongmarkdown/go/v1/rows';
  }

  /** GET rows from the server */
  getRows(): Observable<RowDB[]> {
    return this.http.get<RowDB[]>(this.rowsUrl)
      .pipe(
        tap(_ => this.log('fetched rows')),
        catchError(this.handleError<RowDB[]>('getRows', []))
      );
  }

  /** GET row by id. Will 404 if id not found */
  getRow(id: number): Observable<RowDB> {
    const url = `${this.rowsUrl}/${id}`;
    return this.http.get<RowDB>(url).pipe(
      tap(_ => this.log(`fetched row id=${id}`)),
      catchError(this.handleError<RowDB>(`getRow id=${id}`))
    );
  }

  //////// Save methods //////////

  /** POST: add a new row to the server */
  postRow(rowdb: RowDB): Observable<RowDB> {

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)
    rowdb.Cells = []
    let _Element_Rows_reverse = rowdb.Element_Rows_reverse
    rowdb.Element_Rows_reverse = new ElementDB

    return this.http.post<RowDB>(this.rowsUrl, rowdb, this.httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        rowdb.Element_Rows_reverse = _Element_Rows_reverse
        this.log(`posted rowdb id=${rowdb.ID}`)
      }),
      catchError(this.handleError<RowDB>('postRow'))
    );
  }

  /** DELETE: delete the rowdb from the server */
  deleteRow(rowdb: RowDB | number): Observable<RowDB> {
    const id = typeof rowdb === 'number' ? rowdb : rowdb.ID;
    const url = `${this.rowsUrl}/${id}`;

    return this.http.delete<RowDB>(url, this.httpOptions).pipe(
      tap(_ => this.log(`deleted rowdb id=${id}`)),
      catchError(this.handleError<RowDB>('deleteRow'))
    );
  }

  /** PUT: update the rowdb on the server */
  updateRow(rowdb: RowDB): Observable<RowDB> {
    const id = typeof rowdb === 'number' ? rowdb : rowdb.ID;
    const url = `${this.rowsUrl}/${id}`;

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)
    rowdb.Cells = []
    let _Element_Rows_reverse = rowdb.Element_Rows_reverse
    rowdb.Element_Rows_reverse = new ElementDB

    return this.http.put<RowDB>(url, rowdb, this.httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        rowdb.Element_Rows_reverse = _Element_Rows_reverse
        this.log(`updated rowdb id=${rowdb.ID}`)
      }),
      catchError(this.handleError<RowDB>('updateRow'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error(error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {

  }
}
