// generated by stacks/gong/go/models/controller_file.go
package controllers

import (
	"log"
	"net/http"
	"time"

	"github.com/fullstack-lang/gongmarkdown/go/models"
	"github.com/fullstack-lang/gongmarkdown/go/orm"

	"github.com/gin-gonic/gin"
)

// declaration in order to justify use of the models import
var __Cell__dummysDeclaration__ models.Cell
var __Cell_time__dummyDeclaration time.Duration

// An CellID parameter model.
//
// This is used for operations that want the ID of an order in the path
// swagger:parameters getCell updateCell deleteCell
type CellID struct {
	// The ID of the order
	//
	// in: path
	// required: true
	ID int64
}

// CellInput is a schema that can validate the user’s
// input to prevent us from getting invalid data
// swagger:parameters postCell updateCell
type CellInput struct {
	// The Cell to submit or modify
	// in: body
	Cell *orm.CellAPI
}

// GetCells
//
// swagger:route GET /cells cells getCells
//
// # Get all cells
//
// Responses:
// default: genericError
//
//	200: cellDBResponse
func GetCells(c *gin.Context) {
	db := orm.BackRepo.BackRepoCell.GetDB()

	// source slice
	var cellDBs []orm.CellDB
	query := db.Find(&cellDBs)
	if query.Error != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = query.Error.Error()
		log.Println(query.Error.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// slice that will be transmitted to the front
	cellAPIs := make([]orm.CellAPI, 0)

	// for each cell, update fields from the database nullable fields
	for idx := range cellDBs {
		cellDB := &cellDBs[idx]
		_ = cellDB
		var cellAPI orm.CellAPI

		// insertion point for updating fields
		cellAPI.ID = cellDB.ID
		cellDB.CopyBasicFieldsToCell(&cellAPI.Cell)
		cellAPI.CellPointersEnconding = cellDB.CellPointersEnconding
		cellAPIs = append(cellAPIs, cellAPI)
	}

	c.JSON(http.StatusOK, cellAPIs)
}

// PostCell
//
// swagger:route POST /cells cells postCell
//
// Creates a cell
//
//	Consumes:
//	- application/json
//
//	Produces:
//	- application/json
//
//	Responses:
//	  200: nodeDBResponse
func PostCell(c *gin.Context) {
	db := orm.BackRepo.BackRepoCell.GetDB()

	// Validate input
	var input orm.CellAPI

	err := c.ShouldBindJSON(&input)
	if err != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = err.Error()
		log.Println(err.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// Create cell
	cellDB := orm.CellDB{}
	cellDB.CellPointersEnconding = input.CellPointersEnconding
	cellDB.CopyBasicFieldsFromCell(&input.Cell)

	query := db.Create(&cellDB)
	if query.Error != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = query.Error.Error()
		log.Println(query.Error.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// get an instance (not staged) from DB instance, and call callback function
	orm.BackRepo.BackRepoCell.CheckoutPhaseOneInstance(&cellDB)
	cell := (*orm.BackRepo.BackRepoCell.Map_CellDBID_CellPtr)[cellDB.ID]

	if cell != nil {
		models.AfterCreateFromFront(&models.Stage, cell)
	}

	// a POST is equivalent to a back repo commit increase
	// (this will be improved with implementation of unit of work design pattern)
	orm.BackRepo.IncrementPushFromFrontNb()

	c.JSON(http.StatusOK, cellDB)
}

// GetCell
//
// swagger:route GET /cells/{ID} cells getCell
//
// Gets the details for a cell.
//
// Responses:
// default: genericError
//
//	200: cellDBResponse
func GetCell(c *gin.Context) {
	db := orm.BackRepo.BackRepoCell.GetDB()

	// Get cellDB in DB
	var cellDB orm.CellDB
	if err := db.First(&cellDB, c.Param("id")).Error; err != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = err.Error()
		log.Println(err.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	var cellAPI orm.CellAPI
	cellAPI.ID = cellDB.ID
	cellAPI.CellPointersEnconding = cellDB.CellPointersEnconding
	cellDB.CopyBasicFieldsToCell(&cellAPI.Cell)

	c.JSON(http.StatusOK, cellAPI)
}

// UpdateCell
//
// swagger:route PATCH /cells/{ID} cells updateCell
//
// # Update a cell
//
// Responses:
// default: genericError
//
//	200: cellDBResponse
func UpdateCell(c *gin.Context) {
	db := orm.BackRepo.BackRepoCell.GetDB()

	// Get model if exist
	var cellDB orm.CellDB

	// fetch the cell
	query := db.First(&cellDB, c.Param("id"))

	if query.Error != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = query.Error.Error()
		log.Println(query.Error.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// Validate input
	var input orm.CellAPI
	if err := c.ShouldBindJSON(&input); err != nil {
		log.Println(err.Error())
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	// update
	cellDB.CopyBasicFieldsFromCell(&input.Cell)
	cellDB.CellPointersEnconding = input.CellPointersEnconding

	query = db.Model(&cellDB).Updates(cellDB)
	if query.Error != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = query.Error.Error()
		log.Println(query.Error.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// get an instance (not staged) from DB instance, and call callback function
	cellNew := new(models.Cell)
	cellDB.CopyBasicFieldsToCell(cellNew)

	// get stage instance from DB instance, and call callback function
	cellOld := (*orm.BackRepo.BackRepoCell.Map_CellDBID_CellPtr)[cellDB.ID]
	if cellOld != nil {
		models.AfterUpdateFromFront(&models.Stage, cellOld, cellNew)
	}

	// an UPDATE generates a back repo commit increase
	// (this will be improved with implementation of unit of work design pattern)
	// in some cases, with the marshalling of the stage, this operation might
	// generates a checkout
	orm.BackRepo.IncrementPushFromFrontNb()

	// return status OK with the marshalling of the the cellDB
	c.JSON(http.StatusOK, cellDB)
}

// DeleteCell
//
// swagger:route DELETE /cells/{ID} cells deleteCell
//
// # Delete a cell
//
// default: genericError
//
//	200: cellDBResponse
func DeleteCell(c *gin.Context) {
	db := orm.BackRepo.BackRepoCell.GetDB()

	// Get model if exist
	var cellDB orm.CellDB
	if err := db.First(&cellDB, c.Param("id")).Error; err != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = err.Error()
		log.Println(err.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// with gorm.Model field, default delete is a soft delete. Unscoped() force delete
	db.Unscoped().Delete(&cellDB)

	// get an instance (not staged) from DB instance, and call callback function
	cellDeleted := new(models.Cell)
	cellDB.CopyBasicFieldsToCell(cellDeleted)

	// get stage instance from DB instance, and call callback function
	cellStaged := (*orm.BackRepo.BackRepoCell.Map_CellDBID_CellPtr)[cellDB.ID]
	if cellStaged != nil {
		models.AfterDeleteFromFront(&models.Stage, cellStaged, cellDeleted)
	}

	// a DELETE generates a back repo commit increase
	// (this will be improved with implementation of unit of work design pattern)
	orm.BackRepo.IncrementPushFromFrontNb()

	c.JSON(http.StatusOK, gin.H{"data": true})
}
