// generated by gong
import { Component, OnInit, AfterViewInit, ViewChild, Inject, Optional } from '@angular/core';
import { BehaviorSubject } from 'rxjs'
import { MatSort } from '@angular/material/sort';
import { MatPaginator } from '@angular/material/paginator';
import { MatTableDataSource } from '@angular/material/table';
import { MatButton } from '@angular/material/button'

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData, FrontRepoService, FrontRepo, SelectionMode } from '../front-repo.service'
import { NullInt64 } from '../null-int64'
import { SelectionModel } from '@angular/cdk/collections';

const allowMultiSelect = true;

import { Router, RouterState } from '@angular/router';
import { AnotherDummyDataDB } from '../anotherdummydata-db'
import { AnotherDummyDataService } from '../anotherdummydata.service'

// insertion point for additional imports

// TableComponent is initilizaed from different routes
// TableComponentMode detail different cases 
enum TableComponentMode {
  DISPLAY_MODE,
  ONE_MANY_ASSOCIATION_MODE,
  MANY_MANY_ASSOCIATION_MODE,
}

// generated table component
@Component({
  selector: 'app-anotherdummydatastable',
  templateUrl: './anotherdummydatas-table.component.html',
  styleUrls: ['./anotherdummydatas-table.component.css'],
})
export class AnotherDummyDatasTableComponent implements OnInit {

  // mode at invocation
  mode: TableComponentMode = TableComponentMode.DISPLAY_MODE

  // used if the component is called as a selection component of AnotherDummyData instances
  selection: SelectionModel<AnotherDummyDataDB> = new (SelectionModel)
  initialSelection = new Array<AnotherDummyDataDB>()

  // the data source for the table
  anotherdummydatas: AnotherDummyDataDB[] = []
  matTableDataSource: MatTableDataSource<AnotherDummyDataDB> = new (MatTableDataSource)

  // front repo, that will be referenced by this.anotherdummydatas
  frontRepo: FrontRepo = new (FrontRepo)

  // displayedColumns is referenced by the MatTable component for specify what columns
  // have to be displayed and in what order
  displayedColumns: string[];

  // for sorting & pagination
  @ViewChild(MatSort)
  sort: MatSort | undefined
  @ViewChild(MatPaginator)
  paginator: MatPaginator | undefined;

  ngAfterViewInit() {

    // enable sorting on all fields (including pointers and reverse pointer)
    this.matTableDataSource.sortingDataAccessor = (anotherdummydataDB: AnotherDummyDataDB, property: string) => {
      switch (property) {
        case 'ID':
          return anotherdummydataDB.ID

        // insertion point for specific sorting accessor
        case 'Name':
          return anotherdummydataDB.Name;

        default:
          console.assert(false, "Unknown field")
          return "";
      }
    };

    // enable filtering on all fields (including pointers and reverse pointer, which is not done by default)
    this.matTableDataSource.filterPredicate = (anotherdummydataDB: AnotherDummyDataDB, filter: string) => {

      // filtering is based on finding a lower case filter into a concatenated string
      // the anotherdummydataDB properties
      let mergedContent = ""

      // insertion point for merging of fields
      mergedContent += anotherdummydataDB.Name.toLowerCase()

      let isSelected = mergedContent.includes(filter.toLowerCase())
      return isSelected
    };

    this.matTableDataSource.sort = this.sort!
    this.matTableDataSource.paginator = this.paginator!
  }

  applyFilter(event: Event) {
    const filterValue = (event.target as HTMLInputElement).value;
    this.matTableDataSource.filter = filterValue.trim().toLowerCase();
  }

  constructor(
    private anotherdummydataService: AnotherDummyDataService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of anotherdummydata instances
    public dialogRef: MatDialogRef<AnotherDummyDatasTableComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {

    // compute mode
    if (dialogData == undefined) {
      this.mode = TableComponentMode.DISPLAY_MODE
    } else {
      switch (dialogData.SelectionMode) {
        case SelectionMode.ONE_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.ONE_MANY_ASSOCIATION_MODE
          break
        case SelectionMode.MANY_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.MANY_MANY_ASSOCIATION_MODE
          break
        default:
      }
    }

    // observable for changes in structs
    this.anotherdummydataService.AnotherDummyDataServiceChanged.subscribe(
      message => {
        if (message == "post" || message == "update" || message == "delete") {
          this.getAnotherDummyDatas()
        }
      }
    )
    if (this.mode == TableComponentMode.DISPLAY_MODE) {
      this.displayedColumns = ['ID', 'Edit', 'Delete', // insertion point for columns to display
        "Name",
      ]
    } else {
      this.displayedColumns = ['select', 'ID', // insertion point for columns to display
        "Name",
      ]
      this.selection = new SelectionModel<AnotherDummyDataDB>(allowMultiSelect, this.initialSelection);
    }

  }

  ngOnInit(): void {
    this.getAnotherDummyDatas()
    this.matTableDataSource = new MatTableDataSource(this.anotherdummydatas)
  }

  getAnotherDummyDatas(): void {
    this.frontRepoService.pull().subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        this.anotherdummydatas = this.frontRepo.AnotherDummyDatas_array;

        // insertion point for time duration Recoveries
        // insertion point for enum int Recoveries
        
        // in case the component is called as a selection component
        if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {
          for (let anotherdummydata of this.anotherdummydatas) {
            let ID = this.dialogData.ID
            let revPointer = anotherdummydata[this.dialogData.ReversePointer as keyof AnotherDummyDataDB] as unknown as NullInt64
            if (revPointer.Int64 == ID) {
              this.initialSelection.push(anotherdummydata)
            }
            this.selection = new SelectionModel<AnotherDummyDataDB>(allowMultiSelect, this.initialSelection);
          }
        }

        if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

          let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s" as keyof FrontRepo] as Map<number, AnotherDummyDataDB>
          let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)!

          let sourceField = sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]! as unknown as AnotherDummyDataDB[]
          for (let associationInstance of sourceField) {
            let anotherdummydata = associationInstance[this.dialogData.IntermediateStructField as keyof typeof associationInstance] as unknown as AnotherDummyDataDB
            this.initialSelection.push(anotherdummydata)
          }

          this.selection = new SelectionModel<AnotherDummyDataDB>(allowMultiSelect, this.initialSelection);
        }

        // update the mat table data source
        this.matTableDataSource.data = this.anotherdummydatas
      }
    )
  }

  // newAnotherDummyData initiate a new anotherdummydata
  // create a new AnotherDummyData objet
  newAnotherDummyData() {
  }

  deleteAnotherDummyData(anotherdummydataID: number, anotherdummydata: AnotherDummyDataDB) {
    // list of anotherdummydatas is truncated of anotherdummydata before the delete
    this.anotherdummydatas = this.anotherdummydatas.filter(h => h !== anotherdummydata);

    this.anotherdummydataService.deleteAnotherDummyData(anotherdummydataID).subscribe(
      anotherdummydata => {
        this.anotherdummydataService.AnotherDummyDataServiceChanged.next("delete")
      }
    );
  }

  editAnotherDummyData(anotherdummydataID: number, anotherdummydata: AnotherDummyDataDB) {

  }

  // display anotherdummydata in router
  displayAnotherDummyDataInRouter(anotherdummydataID: number) {
    this.router.navigate(["github_com_fullstack_lang_gongmarkdown_go-" + "anotherdummydata-display", anotherdummydataID])
  }

  // set editor outlet
  setEditorRouterOutlet(anotherdummydataID: number) {
    this.router.navigate([{
      outlets: {
        github_com_fullstack_lang_gongmarkdown_go_editor: ["github_com_fullstack_lang_gongmarkdown_go-" + "anotherdummydata-detail", anotherdummydataID]
      }
    }]);
  }

  // set presentation outlet
  setPresentationRouterOutlet(anotherdummydataID: number) {
    this.router.navigate([{
      outlets: {
        github_com_fullstack_lang_gongmarkdown_go_presentation: ["github_com_fullstack_lang_gongmarkdown_go-" + "anotherdummydata-presentation", anotherdummydataID]
      }
    }]);
  }

  /** Whether the number of selected elements matches the total number of rows. */
  isAllSelected() {
    const numSelected = this.selection.selected.length;
    const numRows = this.anotherdummydatas.length;
    return numSelected === numRows;
  }

  /** Selects all rows if they are not all selected; otherwise clear selection. */
  masterToggle() {
    this.isAllSelected() ?
      this.selection.clear() :
      this.anotherdummydatas.forEach(row => this.selection.select(row));
  }

  save() {

    if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {

      let toUpdate = new Set<AnotherDummyDataDB>()

      // reset all initial selection of anotherdummydata that belong to anotherdummydata
      for (let anotherdummydata of this.initialSelection) {
        let index = anotherdummydata[this.dialogData.ReversePointer as keyof AnotherDummyDataDB] as unknown as NullInt64
        index.Int64 = 0
        index.Valid = true
        toUpdate.add(anotherdummydata)

      }

      // from selection, set anotherdummydata that belong to anotherdummydata
      for (let anotherdummydata of this.selection.selected) {
        let ID = this.dialogData.ID as number
        let reversePointer = anotherdummydata[this.dialogData.ReversePointer as keyof AnotherDummyDataDB] as unknown as NullInt64
        reversePointer.Int64 = ID
        reversePointer.Valid = true
        toUpdate.add(anotherdummydata)
      }


      // update all anotherdummydata (only update selection & initial selection)
      for (let anotherdummydata of toUpdate) {
        this.anotherdummydataService.updateAnotherDummyData(anotherdummydata)
          .subscribe(anotherdummydata => {
            this.anotherdummydataService.AnotherDummyDataServiceChanged.next("update")
          });
      }
    }

    if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

      // get the source instance via the map of instances in the front repo
      let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s" as keyof FrontRepo] as Map<number, AnotherDummyDataDB>
      let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)!

      // First, parse all instance of the association struct and remove the instance
      // that have unselect
      let unselectedAnotherDummyData = new Set<number>()
      for (let anotherdummydata of this.initialSelection) {
        if (this.selection.selected.includes(anotherdummydata)) {
          // console.log("anotherdummydata " + anotherdummydata.Name + " is still selected")
        } else {
          console.log("anotherdummydata " + anotherdummydata.Name + " has been unselected")
          unselectedAnotherDummyData.add(anotherdummydata.ID)
          console.log("is unselected " + unselectedAnotherDummyData.has(anotherdummydata.ID))
        }
      }

      // delete the association instance
      let associationInstance = sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]
      let anotherdummydata = associationInstance![this.dialogData.IntermediateStructField as keyof typeof associationInstance] as unknown as AnotherDummyDataDB
      if (unselectedAnotherDummyData.has(anotherdummydata.ID)) {
        this.frontRepoService.deleteService(this.dialogData.IntermediateStruct, associationInstance)


      }

      // is the source array is empty create it
      if (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance] == undefined) {
        (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance] as unknown as Array<AnotherDummyDataDB>) = new Array<AnotherDummyDataDB>()
      }

      // second, parse all instance of the selected
      if (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]) {
        this.selection.selected.forEach(
          anotherdummydata => {
            if (!this.initialSelection.includes(anotherdummydata)) {
              // console.log("anotherdummydata " + anotherdummydata.Name + " has been added to the selection")

              let associationInstance = {
                Name: sourceInstance["Name"] + "-" + anotherdummydata.Name,
              }

              let index = associationInstance[this.dialogData.IntermediateStructField + "ID" as keyof typeof associationInstance] as unknown as NullInt64
              index.Int64 = anotherdummydata.ID
              index.Valid = true

              let indexDB = associationInstance[this.dialogData.IntermediateStructField + "DBID" as keyof typeof associationInstance] as unknown as NullInt64
              indexDB.Int64 = anotherdummydata.ID
              index.Valid = true

              this.frontRepoService.postService(this.dialogData.IntermediateStruct, associationInstance)

            } else {
              // console.log("anotherdummydata " + anotherdummydata.Name + " is still selected")
            }
          }
        )
      }

      // this.selection = new SelectionModel<AnotherDummyDataDB>(allowMultiSelect, this.initialSelection);
    }

    // why pizza ?
    this.dialogRef.close('Pizza!');
  }
}
